### PR TITLE
Update win module background image

### LINKED ISSUE #5011: Static Image on Win Module Update: Spacing and New Image
Hi @sbsmith86! Per our conversation in Slack re: the centering of text in the win module -- I was talking to Julie about it and she noted that it seems there is an extra space in the code to place the static image -- there is more space between the header image and the static win image than there is between the image and the campaign lead's speech bubble -- which is contributing to the text in the center looking uncentered.

Additionally, the image is looking pixelated, so we are asking creative for an SVG of the win module graphic.

### PR DESCRIPTION
**Pull request by sbsmith86**
#### What's this PR do?
- Removes the win module background image config field on the backend. 
- Adds and sets the win module background pattern as an SVG in the theme.
#### Where should the reviewer start?

`dosomething_campaign.admin.inc` is where the config field is being removed and `dosomething_campaign.install` is where the variable gets deleted permanently.

`_win-module.scss` is where we set the background image in the theme.
#### How should this be manually tested?

Check out a campaign in the win phase and the image should be sharper because we are using an SVG instead of rasterized images. 

In the backend, if you go to `configuration -> dosomething_config -> dosomething_campaign` you should no longer see a field for setting the background image in the win modules settings.
#### What are the relevant tickets?

Fixes #5011 

@DoSomething/front-end for frontend stuff
@angaither for the bender-y removing the config field stuff.

### CODE REVIEW

**Comment by DFurnes** [comment]
Might be good to run the SVGs through an optimizer like [SVGOMG](https://jakearchibald.github.io/svgomg/). Would cut file size pretty significantly!

**Comment by DFurnes** [comment]
:art: :+1: after optimizing those SVGs!

**Comment by sbsmith86** [comment]
@DFurnes updated!

**Comment by DFurnes** [comment]
Awww yissss

**Comment by angaither** [comment]
:+1: :boom: :hammer:

**Pull request merged**
