### PR TITLE
Allow editors manage content aliases.

### PR DESCRIPTION
**Pull request by sergiitk**
#### What's this PR do?
- Grants `editors` role a permission to see, create and edit URL paths on content edit form
#### What are the relevant tickets?

Closes [#DS-412](https://jira.dosomething.org/browse/DS-412).

### CODE REVIEW

**Comment by aaronschachter** [comment]
Do we want all staff to be able to change URL's?  this was restricted from staff by design.

Perhaps a new role would be more appropriate?  cc @mikefantini

**Comment by mikefantini** [comment]
Yeah I'd rather create a new role.

@aaronschachter and I have talked about a few other permissions that might make sense as a sort of super-editor role (like editing the homepage). I'm open to other names but basically this role sit closely with editors but have greater access - between admin and editor.

Open to suggestions on names for this role, but I'd prefer we go that route.

**Comment by aaronschachter** [comment]
Maybe something like `campaigns admin` ?

**Comment by aaronschachter** [comment]
Also @barryclark  -- was Damien granted administrator access? The comment in https://jira.dosomething.org/browse/DS-422 seems to suggest it.  

If so, this PR isn't really relevant anymore and should just be closed.

**Comment by mikefantini** [comment]
yeah campaigns_admin could work, but only if we really restrict the permissions to campaigns relevant functionality. if we want permissions to live outside of campaigns we might want something more generic. editor_plus?

**Comment by aaronschachter** [comment]
Suggestions:
`power editor`
`super editor`

Also, @barryclark @sergii-tkachenko @mshmsh5000 -- thoughts about just granting Damien `administrator` access?  Then no code changes would be needed at all...

**Comment by barryclark** [comment]
@aaronschachter @sergii-tkachenko @mshmsh5000 Sounds good, Aaron.

**Comment by sergiitk** [comment]
@aaronschachter @barryclark @mikefantini So i'm closing this ticket, removing this permission from UK editors and granting admins right to Damien.

**Pull request closed without merging**
