### PR TITLE
Slide title change.

### LINKED ISSUE #6793: Screen 2: Update Header Copy
#### Current Behavior

Header text currently says "This Is How You Do It"
#### Desired Behavior

Text should say "Whoo! You're Signed Up."

(Had a convo w/ Joe about it right before the image file bug hit the site -- prob just didn't have a chance to update. Making it official with an issue)
#### Why This Matters

Since we're only showing screen 2 for this iteration, we want to acknowledge user sign up.

### PR DESCRIPTION
**Pull request by weerd**
#### What's this PR do?

This PR make a quick change to the title for slide 2.
#### How should this be reviewed?

👀 
#### Relevant tickets

Fixes #6793
#### Checklist
- [ ] Tested on staging.

---

@deadlybutter 

cc: @jessleenyc

### CODE REVIEW

**Comment by itsjoekent** [comment]
needs more comments 🚢

**Comment by weerd** [comment]
> needs more comments

:trollface:

**Comment by itsjoekent** [comment]
also a const

**Comment by weerd** [comment]
> also a const

:trollface: for days

**Pull request merged**
