### PR TITLE
Only display zenddesk form on ds.org, not on affiliate sites.

### PR DESCRIPTION
**Pull request by angaither**
Fixes [DOS-124](https://jira.dosomething.org/browse/DOS-124?filter=-1)

cc: @sergii-tkachenko

### CODE REVIEW

**Comment by aaronschachter** [comment]
Code is fine, but why not just disable the module, per comments in the issue?

**Comment by sergiitk** [comment]
:+1:

**Comment by sergiitk** [comment]
@aaronschachter We have no intl-specific deployment code yet (no special features, no modules, no themes).

**Comment by aaronschachter** [comment]
Hmm yeah. Could be done by removing dosomething_zendesk from the dosomething.info dependencies, but ya, the quick fix is fine

**Pull request merged**
