### PR TITLE
School Help Text variable

### PR DESCRIPTION
**Pull request by aaronschachter**
@DFurnes Can you review?

Adds a variable into the DS User admin config form, to pass #3250 over to Team Fender.

### CODE REVIEW

**Comment by aaronschachter** [comment]
Ideally the JS would use the current copy if this variable is not set.

**Comment by DFurnes** [comment]
School finder help can be overridden [here](https://github.com/DoSomething/dosomething/blob/cf1a180a67505979189e419318281db0c3578a78/lib/modules/dosomething/dosomething_signup/dosomething_signup.signup_data_form.inc#L373). We're just toggling visibility of that form element on and off.

**Comment by aaronschachter** [comment]
Got it.  Updating PR now

**Comment by aaronschachter** [comment]
@DFurnes updated

**Comment by DFurnes** [comment]
:shipit:

**Pull request merged**
