### PR TITLE
Remove Alternate BG FID Field on campaigns

### LINKED ISSUE #4026: Remove the Alt BG File fid field.
let's hold off on working on this until next standup at earliest

### PR DESCRIPTION
**Pull request by sbsmith86**
## Fixes #4026

Removes the alternate background FID field on the custom settings page on campaigns.

### CODE REVIEW

**Comment by angaither** [comment]
I think we have some of these set in the DB, should we remove them as well?

**Comment by sbsmith86** [comment]
@angaither ah. Does the update hook i put in remove them?

**Comment by angaither** [comment]
@sbsmith86 let's try

**Comment by angaither** [comment]
I tried it locally, and don't think it removes variables that are already set I think you'll have to do something like this to remove all instances of the variable

```
  db_delete('dosomething_helpers_variable')
      ->condition('entity_type', ’node')
      ->condition('name', ‘alt_bg_fid')
      ->execute();
```

**Comment by sbsmith86** [comment]
@angaither updated! ran the hook locally and check for instances of that field, looks like it was removed.

**Comment by angaither** [comment]
@sbsmith86 cool :+1:

**Comment by sbsmith86** [comment]
Thanks for the help! @angaither

**Pull request merged**
