### PR TITLE
Styles to scale image fluidly.

### LINKED ISSUE #963: 11 Facts - Broken Images
Images are broken on 11 Facts View:

http://staging.beta.dosomething.org/content/11-facts-about-cyber-bullying

### PR DESCRIPTION
**Pull request by weerd**
Added an image style argument to specify a correct image path.

Resolves #963

### CODE REVIEW

**Comment by barryclark** [comment]
INSTA :+1: :bangbang:

**Comment by weerd** [comment]
@blisteringherb can you take a gander at this since I slightly modified the fact_page.module file to add an argument. Just wanna get a thumbs up from ya ;)

**Comment by blisteringherb** [comment]
:+1:

**Comment by weerd** [comment]
Thanks @blisteringherb :)

**Pull request merged**
