### PR TITLE
THE BIG ONE. 

### PR DESCRIPTION
**Pull request by angaither**
Global branch into the dev branch. :earth_asia:

### CODE REVIEW

**Comment by sergiitk** [comment]
Were there any conflicts in this merge you had to solve manually @angaither?

**Comment by sergiitk** [comment]
The code looks good. Will do another test this by building it locally.

**Comment by angaither** [comment]
@sergii-tkachenko nope, no conflicts

**Comment by sergiitk** [comment]
Ok, the build looks good! :+1:

**Pull request merged**
