### PR TITLE
Makes campaign run nodes translatable

### LINKED ISSUE #5987: make campaign run nodes translatable
https://github.com/DoSomething/phoenix/wiki/Making-content-translatable

### PR DESCRIPTION
**Pull request by itsjoekent**
#### What's this PR do?

Makes campaign run translatable
#### What are the relevant tickets?

Fixes #5987

### CODE REVIEW

**Comment by sergiitk** [comment]
:+1:

**Comment by angaither** [comment]
is there anything we need to test in current functionality before this is merged? 
@namimody @mikefantini

**Comment by sergiitk** [comment]
Updates entity translation settings - :+1:

**Comment by itsjoekent** [comment]
oh i should have probably waited for @namimody or @mikefantini 

crap

**Pull request merged**
