### PR TITLE
Removing press field

### PR DESCRIPTION
**Pull request by angaither**
- turning this into a gallery type field. 
- stay tuned for exciting things to come.

### CODE REVIEW

**Comment by aaronschachter** [comment]
Was this pushed to stage?  If not, this looks good and ship it.  But if so we need to add in deleting the field instance.

**Comment by angaither** [comment]
Aw, damn. looks like it was. Alright.

**Comment by angaither** [comment]
@aaronschachter updated

**Comment by aaronschachter** [comment]
looks good

**Pull request merged**
