### PR TITLE
Redis ground work

### PR DESCRIPTION
**Pull request by desmondmorris**
This merge installs redis server into our VM and adds and enables the Drupal redis module.  It also pulls down the predis library.

This does not include any of the default settings that are necessary to wire this up.  These will come in a future merge.

### CODE REVIEW

**Comment by aaronschachter** [comment]
Just checking - any issues with enabling the module but not configuring it?  Errors, etc

**Comment by desmondmorris** [comment]
Should be okay.  This will only work if the cache backends are set in settings.php

@aaronschachter but let me triple check :)

**Comment by aaronschachter** [comment]
If all looks good with the triple check then :+1: 

email password

**Comment by mshmsh5000** [comment]
Great -- I had this set up the same locally. I did have to wrangle the settings, because autoload stuff wasn't happening correctly:

https://gist.github.com/mshmsh5000/9573307

**Comment by desmondmorris** [comment]
@mshmsh5000 that was golden.  thank you

**Comment by mshmsh5000** [comment]
+1 Tested and value added.

**Pull request merged**
