### PR TITLE
Updating vagrant box version to use latest released

### PR DESCRIPTION
**Pull request by weerd**
#### What's this PR do?

This PR updates the version of the `dosomething/phoenix` vagrant box to use the latest released version.
#### Where should the reviewer start?

Just take a :eyes: on quick change.
#### Any background context you want to provide?

I was not sure if there was a specific reason why this wasn't updated. I had tried to `vagrant up` with `v1.0.5` and was running into some weird errors when trying to download the box.

---

@sergii-tkachenko 
cc: @mshmsh5000 @angaither

### CODE REVIEW

**Comment by weerd** [comment]
I'll wait to make the StyleCI changes if it turns out that we do want to bump the version to `1.0.6` cause those are a lot of style updates :\

**Comment by mshmsh5000** [comment]
This duplicates #5554, eh?

**Comment by weerd** [comment]
Oh, haha. :) I will close this then!

**Comment by sergiitk** [comment]
@weerd I'll retest Matt's PR today.

**Comment by weerd** [comment]
Sounds good!

**Pull request closed without merging**
