### PR TITLE
Fixes en global english login/logout experience

### LINKED ISSUE #6488: Error on Log In and Log Out on GL EN
#### Current Behavior

Clicked Log In on GL EN homepage (in Canada via TorGuard), logged in with non-admin account, was brought to the screenshot below. I cleared cache and cookies, and got the same error. Hitting back in the browser brought me back to the homepage which looked fine, and I was logged in. If I tried to log out, I was shown the same screen as when I tried to log in.
#### Desired Behavior

Homepage should simply refresh if I log in from the homepage.
#### Steps to Replicate

Go to somewhere outside the US (not Brazil or MX) and try to log in via the homepage.
#### Why This Matters

Users should be able to log in and out.
#### Countries Affected (optional)

At least GL EN, need to test BR and MX. US EN seems fine.

Need to test if this happens from pitch page as well.
#### OS/Browser (optional)

Chrome.
#### Relevant Screenshots + Links

https://www.dosomething.org/user/logout
image

May be related to: https://github.com/DoSomething/phoenix/issues/5924

cc @mnelson338

### PR DESCRIPTION
**Pull request by itsjoekent**
#### What's this PR do?
- Fixes the too many redirects which occurs on a Canadian user trying to login / out.

In fixing this, I unleashed a bunch of en-global index errors within the campaign module where we didn't do a safety check on the field before accessing the translation lang index. So i just quickly added those checks in.
#### How should this be reviewed?

tell us, how can we review, to test that this works
#### Any background context you want to provide?

The reason this code works because the "user_language" in this case is en-ca, which is not a defined language by our system according to the languages array.
#### Relevant tickets

Fixes #6488

### CODE REVIEW

**Comment by itsjoekent** [comment]
@angaither can you take a look at this?

**Comment by angaither** [comment]
@deadlybutter was this tested from canada? does the experience for other global english sites, and US/BR/MX still work as expected?

**Comment by itsjoekent** [comment]
ah, tested with CA/US but forgot MX/BR. ill give that a try now

**Comment by itsjoekent** [comment]
only noticing 1 problem on BR, if BR translation does not exist its being brought to US translation vs global. not sure if thats related to this change, going to test it on my dev branch

**Comment by itsjoekent** [comment]
ok confirmed ^ is broken on my dev branch, so i guess that needs to be fixed in a different issue. this PR should be good to go however

**Comment by angaither** [comment]
👍 

can you create an issue for [this](https://github.com/DoSomething/phoenix/pull/6530#issuecomment-223070838)

**Comment by itsjoekent** [comment]
yep! and just confirming the 👍 is for this PR to be merged?

**Comment by angaither** [comment]
@deadlybutter yup!

**Comment by itsjoekent** [comment]
https://github.com/DoSomething/phoenix/issues/6532

**Pull request merged**
