### PR TITLE
Unset user.js globally.

### LINKED ISSUE #764: Preprocess JS - User.js
Per description #724 - the login modal on a pitch page does not work unless Drupal's core User module's User.js is removed or renamed manually.

This issue is to handle this programatically, ideally through a `hook_preprocess_js` to avoid messing with core.

### PR DESCRIPTION
**Pull request by angaither**
Fixes #764

cc: @desmondmorris

### CODE REVIEW

**Comment by aaronschachter** [comment]
Question: Would this make sense to define in paraneue_dosomething's template.php?  This issue is only due to neue JS? cc @desmondmorris

**Comment by desmondmorris** [comment]
@aaronschachter  Yes, we are already doing things like this from the theme layer in the paraneue base theme.  The theme layer would be the best place for this.  cc: @DFurnes 

I would not let this block for now though.  It can always be moved.

**Comment by angaither** [comment]
@desmondmorris @aaronschachter @DFurnes 
We could go this route instead https://github.com/DoSomething/paraneue/pull/24

**Comment by angaither** [comment]
closing, unset in https://github.com/DoSomething/paraneue/pull/24

**Pull request closed without merging**
