### PR TITLE
Fixes hotmodule time left

### LINKED ISSUE #5582: Hot Module Shows Date 1 Day Before Deadline
Backend shows:
image

Front end shows:
image

Note that the header photo and the hot module show different dates when the "show end date on pitch page and action page" box is checked. The header photo shows the correct date, and the hot module shows the day before. Therefore, this is not a problem on campaigns without the hot module.

Solve until this is fixed: set deadline on the backend to one day later than the actual deadline, don't show date in header photo.

### PR DESCRIPTION
**Pull request by itsjoekent**
#### What's this PR do?

Fixes the "days left" in hotmodule
#### How should this be manually tested?

Does the hotmodule display correct days left
#### Any background context you want to provide?

It has something to do with user languages, still can't find the exact cause _why_ that matters. For now though this fixes the problem.
#### What are the relevant tickets?

Fixes #5582 
#### Screenshots (if appropriate)

screen shot 2015-11-05 at 10 23 28 am

Note on Git history: "Quick fix for login/logout" was an accidental commit I made on my dev branch which I forgot about, which meant when I check'd out new branches it was there. Because of this I didn't think cherry pick would work and I decided to just revert the commit. Sorry :/

### CODE REVIEW

**Comment by angaither** [comment]
@deadlybutter can you update the PR on why you have to remove the converting to EST if there's less than 8 days left in the campaign? seems like this logic is getting tough to follow

**Comment by itsjoekent** [comment]
code says if days is greater than 8, not less!

As for _why_ this works, when you call the set est timezone function, it actually sets the end time to be the day before it ends, at 23 hours and 59 seconds (this was intentional, theres a pr or issue somewhere in the past describing this, basically it had to deal with calculating time left). 

Using the raw value in the node solves our problem though if we're just getting days left.

Make sense?

**Comment by angaither** [comment]
...okay, seems a little wild though
:+1:

**Comment by itsjoekent** [comment]
It is wild, but i dunno how else to do it cause manipulating time is weird. blame Einstein and dries

**Pull request merged**
