### PR TITLE
Fixes #5554: Updates Vagrant box version

### LINKED ISSUE #5554: Bump Vagrant box version to 1.0.6
https://atlas.hashicorp.com/dosomething/boxes/phoenix

Need to load newest Vagrant box.

### PR DESCRIPTION
**Pull request by mshmsh5000**
#### What's this PR do?

Updates the Vagrantfile's box version to 1.0.6.

https://atlas.hashicorp.com/dosomething/boxes/phoenix/versions/1.0.6
#### Where should the reviewer start?

One-line change to Vagrantfile.
#### How should this be manually tested?

```
% vagrant destroy
% vagrant up
```
#### Any background context you want to provide?

We need to update the Vagrant box to pull in new SSH keys for contributors. This is not optimal.
#### What are the relevant tickets?
#5554
#### Screenshots (if appropriate)

N/A
#### Questions:

N/A

### CODE REVIEW

**Comment by mshmsh5000** [comment]
Note that @sergii-tkachenko tried the new box version and was unsuccessful.

**Comment by sergiitk** [comment]
It turned out to be successful, but took unusual amount of time on the boot phase:

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: dosomething
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
Got different reports about installed GuestAdditions version:
```

**Comment by sergiitk** [comment]
Ref DoSomething/tower#168.

**Comment by weerd** [comment]
@sergii-tkachenko I just ran it and seemed to work fine for me...

**Comment by sergiitk** [comment]
I just created a new version based on latest Ubuntu and including additional ssh keys.
Let's just skip this version (the inspiration sponsored by PHP skipping v6 :smile:).

**Pull request closed without merging**
