### PR TITLE
Disable CSP stuffz

### LINKED ISSUE #6981: Prevent Facebook from violating the content security policy
screen shot 2016-08-31 at 10 26 36 am

### PR DESCRIPTION
**Pull request by angaither**
#### What's this PR do?

Unchecks some boxes so that console isn't filled up with bogus errors. 
#### How should this be reviewed?

here's what I unchecked 
image
#### Any background context you want to provide?

since @sergii-tkachenko isn't able to focus on this, going to disable for now so we aren't blowing up console logs with these notifications. 
#### Relevant tickets

Refs #5783 Fixes #6981

### CODE REVIEW

**Comment by DFurnes** [comment]
👍 😌

**Comment by sergiitk** [comment]
Wouldn't it better to just disable the module?

**Comment by angaither** [comment]
@sergii-tkachenko yes, but AFAIK I don't think we have the ability to disable modules in our deploy, we only [enable modules](https://github.com/DoSomething/phoenix/blob/3759e46a598d71c0e72781be5dd3c17e47771ad4/bin/ds#L290)

**Comment by DFurnes** [comment]
I believe we also use the Security Kit module for other things, don't we?

**Comment by sergiitk** [comment]
@DFurnes Good catch. 👍

**Pull request merged**
