### PR TITLE
Revising a term and updating styles with how it is rendered.

### PR DESCRIPTION
**Pull request by weerd**
Refs #5517
#### What's this PR do?

This PR revises a term in the **paraneue_dosomething.pot** file and associated term in the `t()` function wherever it is output. It also adjusts some styles related to how the term is output in the Reportback gallery. There is an issue with include html tags (or even `\r\n` characters) in a term imported via PO file into Drupal, so the best solution was to remove the extra phrasing (which was planning on being shortened anyway).
#### Where should the reviewer start?

Take a quick :eyes: 
#### How should this be manually tested?

Will be tested on Thor.
#### What are the relevant tickets?
#5517

---

@angaither 

cc: @DFurnes

### CODE REVIEW

**Comment by DFurnes** [comment]
A lovely new coat of paint! :art:

**Comment by angaither** [comment]
what happened to the :cool: kids? 
:+1:

**Comment by weerd** [comment]
All the cool kids realized we're all in this together! :globe_with_meridians:

**Comment by weerd** [comment]
#global

**Pull request merged**
