### PR TITLE
Revert "Add 'uk_birthday' validator that accepts DD/MM/YYYY format."

### PR DESCRIPTION
**Pull request by DFurnes**
Reverts DoSomething/dosomething#3084, since we're blocked on Features issue with date formatting on the backend.

### CODE REVIEW

**Comment by sergiitk** [comment]
:+1:

**Comment by sergiitk** [comment]
Btw, I've had some code standards — please assign me to review next time we're merging it back. @DFurnes

**Comment by DFurnes** [comment]
Will do!

**Comment by sergiitk** [comment]
Thanks!

**Pull request merged**
