### PR TITLE
Pin messagebroker php lib download tag to previous

### PR DESCRIPTION
**Pull request by angaither**
#### What's this PR do?

pin messagebroker php lib
#### How should this be reviewed?

`ds build`
#### Any background context you want to provide?

let's fix prod!
#### Relevant tickets

Fixes #production 
#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

### CODE REVIEW

**Comment by sergiitk** [comment]
Testing it locally.

**Comment by deezone** [comment]
👍

**Comment by sergiitk** [comment]
Confirming that now it's cloning the HEAD:

```
messagebroker-phplib cloned from https://github.com/DoSomething/messagebroker-phplib.git. [ok]
```

**Comment by angaither** [comment]
@sergii-tkachenko good to merge?

**Comment by sergiitk** [comment]
Still testing.

**Comment by sergiitk** [comment]
```
❯ grep version html/profiles/dosomething/libraries/messagebroker-phplib/composer.json
    "version": "0.2.9",
```

👍

**Pull request merged**
