### PR TITLE
Progress on fixing image upload issue.

### LINKED ISSUE #3712: Reportback Cropping: image_gd_create() error
There is a bug that sometimes gets shown when cropping and image. It seems to be tied to when the image cropping script things that the crop area selected does not fully cover the image. 
image_gd_create

### PR DESCRIPTION
**Pull request by weerd**
## Fixes #3712

My suspicions were correct! After troubleshooting for a bit, found the `dosomething_reportback_image_edit($image, $x, $y, $width, $height, $rotate = NULL)` requires values for the `x`, `y`, `width`, `height`, that then get passed to `image_crop($image, $x, $y, $width, $height)`.

So, I'm passing along default `value` values for the hidden inputs. An alternative could be to set the defaults for the parameters in the function, but not sure what the best call is here. 

Either solution would work. I've also tested this using the technique described in the issue to reproduce the error and the error is gone :dancer: 

@DoSomething/front-end 
@angaither 
@barryclark

### CODE REVIEW

**Comment by barryclark** [comment]
Nice one, @weerd!

**Comment by angaither** [comment]
@weerd when does this happen? don't you always send in the values once the user crops?

**Comment by weerd** [comment]
@angaither  Nope. Not if the API is not supported (example: IE8/9). There's no crop modal for browsers that don't support the File API, thus we just get the file and send it through without obtaining any of the `x, y, width, height, rotation` info.

**Comment by angaither** [comment]
This works! :+1:

**Pull request merged**
