### PR TITLE
Restores global commits

### PR DESCRIPTION
**Pull request by sergiitk**
Semi-automatic branch restore:
`git cherry-pick -X theirs 97b09a9 a66511b 22d4a82 112250b 8cc9996 9f79583 60107d1 259cbce 250fb47 5abd092 b740dfb da1ad14 c851117 60ddc02 0df6936 0dce43f 45f4a1f f1be294 f22a95d 04ce78b 55affc5 6d7e3d9`

cc @blisteringherb @sheyd @deadlybutter @DFurnes

### CODE REVIEW

**Comment by sheyd** [comment]
Giving tacit :+1: pending actual review by people who've touched the code.

**Comment by itsjoekent** [comment]
im looking through these, they all appear to be different changes even though they share the same commit name. while I dont like this I'm not sure what else we can quickly do to resolve it.

**Comment by sergiitk** [comment]
@deadlybutter are you talking about 4faa98f and 1eed4b3?

**Comment by itsjoekent** [comment]
no, I'm referring to almost every commit there. they all have duplicate commits with the same name. different changes/hash, same title.

**Comment by sergiitk** [comment]
Hm. I see it now.

**Comment by itsjoekent** [comment]
- Exporting language prefix settings and url alias settings 
- 5130: BR, MX path patterns; default lang
- Fixes logout URL
- Uses L instead of printing URL
- Adds ID's
- 5183: Code cleanup from PR comments
- #5183: Refactors the 'en-global' into a constant (DOSOMETHING_GLOBAL_
- Removes en-global path prefix for Global English.
- Exports English language to Global feature, sets path prefix to `us`.

Each of these has a duplicate commit sharing the same name.

**Comment by sergiitk** [comment]
I think these are results of resolving conflicts and we should just check the final output.

**Comment by sergiitk** [comment]
Acrually, let me just squash this commits and see what happens.

**Comment by itsjoekent** [comment]
gotcha, again, I dont know if it needs to block the merge, I just wish git history wasnt gonna be so ugly

**Comment by sergiitk** [comment]
@deadlybutter You're right, something is wrong with this commits: I based the list of commits on #5364 and it looks like it has the same issue. CC @sheyd

**Comment by sheyd** [comment]
@sergii-tkachenko Don't you have to base these off of https://github.com/DoSomething/phoenix/pull/5375 ?

**Comment by sergiitk** [comment]
Ok I replaced now this changes with `git cherry pick b740dfb da1ad14 c851117 60ddc02 0df6936 0dce43f 45f4a1f f1be294 f22a95d 04ce78b 55affc5 6d7e3d9`

**Comment by sergiitk** [comment]
@sheyd No, #5375 is just one commit and there's no way to find individual commit hashes in there.

**Comment by itsjoekent** [comment]
looks :ok:

**Comment by sergiitk** [comment]
Diff stats #5364:

```
Showing  7 changed files  with 275 additions and 31 deletions.
```

Diff stats #5381:

```
Showing  7 changed files  with 275 additions and 31 deletions.
```

Looks :+1:

**Comment by sheyd** [comment]
Looks like a cleaner commit to me :) Yay @sergii-tkachenko

**Pull request merged**
