### PR TITLE
Update to latest Drupal 7 release... maybe.

### PR DESCRIPTION
**Pull request by DFurnes**
#### What's this PR do?

This pull request updates to the latest Drupal 7 release. This release includes [a fix for those ugly "session destroy" errors](https://www.drupal.org/node/2638016) that were showing up on staging, and presumably some other PHP 7 fixes according to the comments in that discussion.
#### How should this be reviewed?

It should build and not have those errors after you build.  🐛🔨
#### Any background context you want to provide?

I am currently seeing some nasty Drush errors :fearful: when testing this on my local and trying to pull the staging database. ~~The build itself works as expected~~ No everything is broken, see build errors below. I get the same errors when trying to build on the dev branch, though, so maybe it's just an unrelated problem on my end.

```
dosomething@dev:/var/www/dev.dosomething.org$ ds pull stage --db
Dropping local DB
Do you really want to drop all tables in the database dosomething? (y/n): y
Pulling down db from staging
The external command could not be executed due to an application error.                                                                                               [error]
Illegal string offset 'site' backend.inc:1032                                                                                                                         [warning]
                                                                             [error]ey).
, code: 255)
Error: no database record could be found for source @ds.staging      
```
#### Relevant tickets

References DoSomething/northstar#457.
#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love
- [ ] Post a message in #phoenix if this includes something that causes a rebuild!

### CODE REVIEW

**Comment by DFurnes** [comment]
This [StackOverflow answer](http://drupal.stackexchange.com/questions/170490/drush-sql-sync-failing-with-illegal-string-offset-site-backend-inc1030) suggests that adding a value to the Drush config on the server would fix the error. I tried this on staging's `/home/dosomething/.drush/ds.aliases.drushrc.php` and it did not seem to help (reverted afterwards).

**Comment by DFurnes** [comment]
Oh wait, I do seem to be getting a ton of errors on the `ds build --install` step as well. I get the exact same errors when trying to build on the dev branch though, so not sure what to make of it. 🤔

```
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                             [ok]
Exception: none.:                                                                                                                                                        [error]

New Relic PHP Library missing. Check <a href="https://newrelic.com/docs/php/new-relic-for-php">Install New Relic for PHP</a> for more information. in
/var/www/dev.dosomething.org/html/includes/install.core.inc:773
Stack trace:
#0 /var/www/dev.dosomething.org/html/includes/install.core.inc(471): install_verify_requirements(Array)
#1 /var/www/dev.dosomething.org/html/includes/install.core.inc(339): install_run_task(Array, Array)
#2 /var/www/dev.dosomething.org/html/includes/install.core.inc(77): install_run_tasks(Array)
#3 /home/dosomething/.composer/vendor/drush/drush/includes/drush.inc(723): install_drupal(Array)
#4 /home/dosomething/.composer/vendor/drush/drush/includes/drush.inc(709): drush_call_user_func_array('install_drupal', Array)
#5 /home/dosomething/.composer/vendor/drush/drush/commands/core/drupal/site_install_7.inc(82): drush_op('install_drupal', Array)
#6 /home/dosomething/.composer/vendor/drush/drush/commands/core/site_install.drush.inc(291): drush_core_site_install_version('dosomething', Array)
#7 /home/dosomething/.composer/vendor/drush/drush/includes/command.inc(361): drush_core_site_install('dosomething')
#8 /home/dosomething/.composer/vendor/drush/drush/includes/command.inc(212): _drush_invoke_hooks(Array, Array)
#9 /home/dosomething/.composer/vendor/drush/drush/includes/command.inc(180): drush_command('dosomething')
#10 /home/dosomething/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64): drush_dispatch(Array)
#11 /home/dosomething/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#12 /home/dosomething/.composer/vendor/drush/drush/drush.php(11): drush_main()
#13 {main}
Granting basic permissions...
Command role-add-perm needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.            [error]
The drush command 'rap anonymous user access content' could not be executed.                                                                                          [error]
Command role-add-perm needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.            [error]
The drush command 'rap authenticated user access content' could not be executed.                                                                                      [error]
Rebuilding node permissions
PHP Fatal error:  Uncaught Error: Call to undefined function cache_get() in /var/www/dev.dosomething.org/html/includes/module.inc:754
Stack trace:
#0 /var/www/dev.dosomething.org/html/includes/module.inc(954): module_implements('system_theme_in...')
#1 /var/www/dev.dosomething.org/html/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /var/www/dev.dosomething.org/html/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /var/www/dev.dosomething.org/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/dev.dosomething.org/html/includes/bootstrap.inc(2857): _drupal_maintenance_theme()
#5 /var/www/dev.dosomething.org/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/dev.dosomething.org/html/includes/bootstrap.inc(2594): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/dev.dosomething.org/html/includes/module.inc on line 754
Drush command terminated abnormally due to an unrecoverable error.                                                                                                    [error]
Error: Uncaught Error: Call to undefined function cache_get() in /var/www/dev.dosomething.org/html/includes/module.inc:754
Stack trace:
#0 /var/www/dev.dosomething.org/html/includes/module.inc(954): module_implements('system_theme_in...')
#1 /var/www/dev.dosomething.org/html/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /var/www/dev.dosomething.org/html/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /var/www/dev.dosomething.org/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/dev.dosomething.org/html/includes/bootstrap.inc(2857): _drupal_maintenance_theme()
#5 /var/www/dev.dosomething.org/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/dev.dosomething.org/html/includes/bootstrap.inc(2594): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/dev.dosomething.org/html/includes/module.inc, line 754
Reverting all features
The drush command 'fra' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.                       [error]
Removing install.php...
Running drush from directory /var/www/dev.dosomething.org/html
Drush status:
 Drupal version         :  7.51                                                     
 Site URI               :  http://default                                           
 Database driver        :  mysql                                                    
 Database hostname      :  localhost                                                
 Database port          :                                                           
 Database username      :  root                                                     
 Database name          :  dosomething                                              
 PHP executable         :  /usr/bin/php                                             
 PHP configuration      :  /etc/php/7.0/cli/php.ini                                 
 PHP OS                 :  Linux                                                    
 Drush script           :  /home/dosomething/.composer/vendor/drush/drush/drush.php 
 Drush version          :  7.3.0                                                    
 Drush temp directory   :  /tmp                                                     
 Drush configuration    :                                                           
 Drush alias files      :  /home/dosomething/.drush/ds.aliases.drushrc.php          
 Drupal root            :  /var/www/dev.dosomething.org/html                        
 Site path              :  sites/default                                            

Adding role to admin user...
Command user-add-role needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.            [error]
The drush command 'user-add-role administrator 1' could not be executed.                                                                                              [error]
Updating database...
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dosomething.system' doesn't exist in                                                         [error]
/var/www/dev.dosomething.org/html/includes/database/database.inc:2227
Stack trace:
#0 /var/www/dev.dosomething.org/html/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /var/www/dev.dosomething.org/html/includes/database/database.inc(697): DatabaseStatementBase->execute(Array, Array)
#2 /var/www/dev.dosomething.org/html/includes/database/database.inc(2406): DatabaseConnection->query('SELECT name, sc...', Array, Array)
#3 /var/www/dev.dosomething.org/html/includes/install.inc(155): db_query('SELECT name, sc...', Array)
#4 /var/www/dev.dosomething.org/html/includes/update.inc(146): drupal_get_installed_schema_version('system')
#5 /home/dosomething/.composer/vendor/drush/drush/commands/core/drupal/update_7.inc(162): update_prepare_d7_bootstrap()
#6 /home/dosomething/.composer/vendor/drush/drush/commands/core/drupal/update_7.inc(225): update_main_prepare()
#7 /home/dosomething/.composer/vendor/drush/drush/commands/core/core.drush.inc(457): update_main()
#8 /home/dosomething/.composer/vendor/drush/drush/includes/command.inc(361): drush_core_updatedb()
#9 /home/dosomething/.composer/vendor/drush/drush/includes/command.inc(212): _drush_invoke_hooks(Array, Array)
#10 /home/dosomething/.composer/vendor/drush/drush/includes/command.inc(180): drush_command()
#11 /home/dosomething/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64): drush_dispatch(Array)
#12 /home/dosomething/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#13 /home/dosomething/.composer/vendor/drush/drush/drush.php(11): drush_main()
#14 {main}
Enabling modules in dosomething.info
PHP Fatal error:  Uncaught Error: Call to undefined function cache_get() in /var/www/dev.dosomething.org/html/includes/module.inc:754
Stack trace:
#0 /var/www/dev.dosomething.org/html/includes/module.inc(954): module_implements('system_theme_in...')
#1 /var/www/dev.dosomething.org/html/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /var/www/dev.dosomething.org/html/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /var/www/dev.dosomething.org/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/dev.dosomething.org/html/includes/bootstrap.inc(2857): _drupal_maintenance_theme()
#5 /var/www/dev.dosomething.org/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/dev.dosomething.org/html/includes/bootstrap.inc(2594): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/dev.dosomething.org/html/includes/module.inc on line 754
Drush command terminated abnormally due to an unrecoverable error.                                                                                                    [error]
Error: Uncaught Error: Call to undefined function cache_get() in /var/www/dev.dosomething.org/html/includes/module.inc:754
Stack trace:
#0 /var/www/dev.dosomething.org/html/includes/module.inc(954): module_implements('system_theme_in...')
#1 /var/www/dev.dosomething.org/html/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /var/www/dev.dosomething.org/html/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /var/www/dev.dosomething.org/html/includes/theme.maintenance.inc(57): list_themes()
#4 /var/www/dev.dosomething.org/html/includes/bootstrap.inc(2857): _drupal_maintenance_theme()
#5 /var/www/dev.dosomething.org/html/includes/errors.inc(179): drupal_maintenance_theme()
#6 /var/www/dev.dosomething.org/html/includes/bootstrap.inc(2594): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /var/www/dev.dosomething.org/html/includes/module.inc, line 754
Reverting Features
The drush command 'fra' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.                       [error]
Clearing caches...
No Drupal site found, only 'drush' cache was cleared.
```

**Comment by sbsmith86** [comment]
Not really helpful but just wanted to note that I have been seeing these errors as well. @sergii-tkachenko told me to just pull down the db so I didn't have to worry about the install

**Comment by angaither** [comment]
@DFurnes I will try a build on the dev branch before pulling this update.

**Comment by angaither** [comment]
a plain build on `dev` worked, now for the kicker with an `--install`

**Comment by angaither** [comment]
it seems like the `--install` flag worked, meow I will try this with the updated drupal version

**Comment by DFurnes** [comment]
I just remembered that the build errors are the same ones I was getting in #6561, which turned out to be an expected part of the build process. Unfortunately I still seem to get the same `Illegal string offset 'site' backend.inc:1032` error on the `ds pull stage --db` step when on the dev branch. 😞

**Comment by DFurnes** [comment]
Aaaaaand thanks to @angaither for pointing out that there's a FAQ for that in the wiki. 😅 I just successfully re-built and pulled staging on my local and all looks well.

**Comment by angaither** [comment]
@DFurnes SAME!

**Pull request merged**
