### PR TITLE
Adding and enabling modules needed for POT related work.

### PR DESCRIPTION
**Pull request by weerd**
#### What's this PR do?

This PR adds the POEditor module to list of contrib modules needed and enables both the POEditor module and the POTX module.
#### Where should the reviewer start?

Just giving a quick look at the code to make sure modules are getting activated in the right place. Not sure if I need to specify anywhere else for Drupal to enable these two modules.

---

@angaither 
CC: @sergii-tkachenko  @mshmsh5000

### CODE REVIEW

**Comment by sergiitk** [comment]
@weerd looks good, bud you need to rebase this branch agains `dev` and push-force the changes here.

**Comment by weerd** [comment]
Cool cool. Thanks @sergii-tkachenko. I'll push up update in a minute :dancer:

**Comment by sergiitk** [comment]
Woah. This isn't right. Can you redo the change in clean branch and re-create pull request?

**Comment by weerd** [comment]
yeah, ok. something looked off :\

**Comment by angaither** [comment]
@sergii-tkachenko what's wrong with this PR, it has the changes of dev in it?

**Comment by sergiitk** [comment]
The auto-merge was not available with this PR @angaither .

**Comment by angaither** [comment]
@sergii-tkachenko we reopened it and it seems ok

**Comment by sergiitk** [comment]
But it's **impossible** to figure out the actual change made in the list like this:
image
We should never merge such PRs, it defies the whole idea of tracking changes and code reviews.

**Comment by angaither** [comment]
... this isn't a merge. 
he rebased dev into this branch, and global branch is 31 commits behind the dev branch

**Comment by angaither** [comment]
in order to keep global up to date with dev, we either have to force push a rebase (which isn't the best idea) or do merges of dev into global

**Comment by sergiitk** [comment]
Yes, but he should've merge global in his branch.

**Comment by sergiitk** [comment]
Sure, but this merges must not be in PRs dedicated for other changes.

**Comment by angaither** [comment]
I agree, but you asked him to rebase with dev. 
screen shot 2015-10-01 at 11 16 50 am

**Comment by sergiitk** [comment]
My fault.

**Comment by sergiitk** [comment]
I didn't notice it's targeted to global branch.

**Pull request merged**
