### PR TITLE
Adds toLowerCase() for the onboarding country check

### PR DESCRIPTION
**Pull request by itsjoekent**
#### What's this PR do?

title ^
#### How should this be reviewed?

does onboarding show for MX
#### Any background context you want to provide?

apparently country can be capital. lets make it all lower case 👌 
#### Relevant tickets

Fixes #
#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

### CODE REVIEW

**Comment by weerd** [comment]
👍

**Comment by itsjoekent** [comment]
actually wait @weerd shouldnt this be user.info.country?

**Comment by DFurnes** [comment]
I think it'd make sense to fix `dosomething_global_convert_country_to_language` to always return either an uppercase or lowercase string, rather than patching it here.

**Comment by itsjoekent** [comment]
im pretty sure its always upper case, i think in mod headers ive just been testing with lower case so its bad habbit.

**Comment by itsjoekent** [comment]
@DFurnes @weerd did a bit more refactoring, i think this makes more sense

**Comment by DFurnes** [comment]
👍 ⛵

**Pull request merged**
