### PR TITLE
DoSomething Payment module + Stripe integration

### PR DESCRIPTION
**Pull request by aaronschachter**
Adds a new DoSomething Payment module which will provide a new custom block for Donation Form, which uses Stripe.

Also adds the Stripe PHP Library for said Donation Form into the build / libraries.

Doesn't actually do anything yet though, but sets up place to add code for #3312

### CODE REVIEW

**Comment by sergiitk** [comment]
The install file is empty. You can add uninstall function there and remove dosomething_payment_\* vars.

**Comment by aaronschachter** [comment]
Yeah.. I totally meant to do that. Good catch!

**Comment by aaronschachter** [comment]
@sergii-tkachenko updated!

**Comment by sergiitk** [comment]
:+1: Great!

**Pull request merged**
