### PR TITLE
Issue2718 add reportback image url to mbp payload

### LINKED ISSUE #2718: Add reportback image path to mbp payload
Add the path to the image related to a campaign report back to the payload sent to mbp `dosomething_mbp_request('campaign_reportback', $params)` requests.

### PR DESCRIPTION
**Pull request by deezone**
Fixes #2718

Adds report back image markup value to payload values sent to mbp.

### CODE REVIEW

**Comment by aaronschachter** [comment]
:+1:

**Comment by deezone** [comment]
It's not clear to me how ReportbackEntityController->save gets called to trigger the `dosomething_reportback_mbp_request($entity);` call? Is there some Drupal magic connecting `function dosomething_reportback_save()` to the class?

**Comment by aaronschachter** [comment]
Yes, this one actually is some Drupal magic.  We create a reportback entity in `dosomething_reportback_save` and use the save method on it: https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_reportback/dosomething_reportback.module#L380

And in the ReportbackentityController class, we override the `save` method: https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_reportback/includes/dosomething_reportback.inc#L376

**Comment by deezone** [comment]
Gotta love OO. Thanks for the explanation, makes perfect sense now that you point it out.

**Pull request merged**
