### PR TITLE
Reportback function updates

### LINKED ISSUE #6054: Update any create/edit/delete functions for SignUps & Reportbacks to account for run_nid
Refs #5993

Need to go through the signup and reportback processes (DS App & API) and update each function to now also account for the new `run_nid` and the unique combinations with `uid` and `nid` when creating entitites.

### PR DESCRIPTION
**Pull request by weerd**
Fixes #6054 
Refs #5991
#### What's this PR do?

There are a series of function related to Reportback saving etc, that needed to be accounted for with updates regarding the campaign `run_nid` data. This PR updates all the functions involved.
#### Where should the reviewer start?

Might be best to review it in order of [commits](https://github.com/DoSomething/phoenix/pull/6088/commits).
#### How should this be manually tested?

You can pull down the branch, clear cache and try submitting a few reportbacks. Check that the database is correctly updated with the appropriate `run_nid` on the `dosomething_reportbacks` table.
#### What are the relevant tickets?
#6054
#5991

---

@angaither 

CC: @deadlybutter  @DFurnes

### CODE REVIEW

**Comment by itsjoekent** [comment]
Is it worth waiting to merge this to go alongside https://github.com/DoSomething/phoenix/pull/6080 ? (diego skip to Andrea's first comment)

**Comment by weerd** [comment]
Ok to merge? I've checked locally and things seem to be working ok...

**Comment by angaither** [comment]
if you're sure it works :+1:

**Comment by weerd** [comment]
@angaither ominous thumbs up, haha

**Pull request merged**
