### PR TITLE
Removes unneeded feature file

### PR DESCRIPTION
**Pull request by deezone**
Feature reverts should stop complaining with the removal of this unneeded feature file. The `dosomething_mbp` module do not require features exported to files as it does not have UI components.

### CODE REVIEW

**Comment by desmondmorris** [comment]
+1 ship it

**Comment by aaronschachter** [comment]
WAIT there is an `administer message broker` permission defined.

**Comment by aaronschachter** [comment]
It was formerly defined by `dosomething_user` and there was an issue to move it into DS MBP so `message_broker` was not a dependecy of `dosomething_user`.  I will find the related issues.

**Comment by aaronschachter** [comment]
See https://github.com/DoSomething/dosomething/issues/1748#issuecomment-40020391. 

The `dosomething_mbp` module is not properly defining this because it's not including the relevant features.inc.

The proper way to fix would be to `drush -y fe dosomething_mbp "user_permission: administer message broker"` -- not sure if thats correct syntax for the permission, you can find it by using `drush fc`

**Comment by aaronschachter** [comment]
This module SHOULD define the permissions, because they are needed for administrators, and message broker is already a dependency.

**Comment by desmondmorris** [comment]
/me retracts previous comment due to ignorance

**Comment by deezone** [comment]
Should the permissions be defined in `message_broker_producer` or `dosomething_mbp`? All of the admin UI lives in `message_broker_producer`. `dosomething_mbp` has all of the DS specific code based logic.

**Comment by aaronschachter** [comment]
`dosomething_mbp`, because the permission for the "administrator role" is DS specific. `message_broker_producer` is considered a contrib module.

**Comment by deezone** [comment]
OK, sounds good.

**Comment by aaronschachter** [comment]
@DeeZone You'll have to do some investigation with `dosomething_user`.  Right now `drush fc --exported user_permission` shows the `user_permission:administer message_broker_producer` defined in `dosomething_user.`  However there was a PR (#1838) that tried to remove this and add it in, which seems to be causing `dosomething_user` to be unable to fully revert. #1838 never added a features.inc include. Once you get it out of `dosomething_user`, use the `drush fe` command to export it into `dosomething_mbp` properly.

**Pull request closed without merging**
