### PR TITLE
Removes mailsystem

### LINKED ISSUE #1759: Remove mailsystem from profile and make
According to @DeeZone we don't need this module. so let's kill it.

### PR DESCRIPTION
**Pull request by deezone**
Fixes #1759

The Mail System module is no longer needed as all mail functionality is now running through the Message Broker. The Message Broker handles all communication with the Mailchimp and Mandrill services.

### CODE REVIEW

**Comment by aaronschachter** [comment]
Looks good :+1:

**Comment by angaither** [comment]
What's the process for removing modules in production, do we need to do anything after this deployment?

**Comment by aaronschachter** [comment]
Ohh yeah.  Actually we should disable and uninstall now before this is removed from codebase and everything breaks. @DeeZone can you disable and uninstall on stage and prod using UI (or drush) ?

**Comment by deezone** [comment]
@aaronschachter 
mailsystem is a dependency for DoSomething User. Is it **not** possible to disable / uninstall the mail system module without disabling the DoSomething User module? Perhaps this needs to be a two step deployment process?

**Comment by aaronschachter** [comment]
I think you're right @DeeZone.. perhaps the first PR should just remove the dependency, so we can disable and uninstall.

**Comment by deezone** [comment]
@aaronschachter Step one, removal of DoSomething User dependencyy on Mail System in place.

**Comment by aaronschachter** [comment]
:+1:

**Pull request merged**
