### PR TITLE
Vagrant on Ansible.

### PR DESCRIPTION
**Pull request by sergiitk**
#### What's this PR do?
- Configures vagrant to use [newest box](/DoSomething/vagrant-platform) built with Ansible
#### Testing
- Checkout this branch
- Start Vagrant `vagrant up`
- Log into VM `vagrant ssh`
- Run `setup-www`
- Change directory to `cd /var/www/dev.dosomething.org`
- Build project as usual `bin/ds build --install` or `bin/ds build && bin/ds pull --db`
##### New and updated software:
- Ubuntu 14.04
- Nginx/php-fpm instead of Apache/mod_php
- Drush 6.5.0
- PHP 5.5.9-1
- MySQL 5.5.41
##### Changes:
- Now default user is `dosomething`
- Default web folder changed to `/var/www/dev.dosomething.org`
##### Not ready / In progress:
- Solr
- Varnish
- Https

### CODE REVIEW

**Comment by sergiitk** [comment]
CC @blisteringherb @aaronschachter @mshmsh5000 @weerd @DFurnes @angaither @sbsmith86 @DeeZone

**Comment by DFurnes** [comment]
Seems to be working nicely for me, using the NFS mount option! :tada: 

I did notice some errors appearing on page loads though, not sure if it's related to the new Vagrant box:

screen shot 2015-03-10 at 1 26 19 pm

**Comment by sergiitk** [comment]
Thank you @DFurnes! Yes, I also noticed this errors, probably Solr related. Will investigate this when all software will be in place.

**Comment by sergii-tkachenko** [comment]
New SequelPro settings:


image

**Comment by sergiitk** [comment]
New SequelPro settings:

image

**Pull request merged**
