### PR TITLE
Hotfix for #1840 - remove signup as entity

### PR DESCRIPTION
**Pull request by aaronschachter**
:warning: Not ready to merge, opened for visibility.

This is making things die.

### CODE REVIEW

**Comment by aaronschachter** [comment]
We replaced staging DB with a version from 6am, before I ran the update hook this morning. However the error is still occurring.

Locally: I restored the DB using `ds pull stage`, cleared cache with these changes, and things were working.  Then running after dosomething_signup_update_7004, borked again.  

Retracing my steps to try and replicate (taking the same database DB from stage) and now its not working.  :trollface:

**Comment by aaronschachter** [comment]
Also FYI @DFurnes never ran the update hook, but cleared cache and his local borked too.

**Comment by desmondmorris** [comment]
@aaronschachter is this PR still relevant?  Wondering if it is safe to update the international tier.  Releated to #1850

**Comment by aaronschachter** [comment]
Good call, dev branch should be in good shape now.

**Pull request closed without merging**
