### PR TITLE
Adds advertising tracking for FB & Twitter

### PR DESCRIPTION
**Pull request by itsjoekent**
#### What's this PR do?
- Adds advertising tracking for FB & Twitter
- (Replaces/Removes social auth prototype code)

#### How should this be reviewed?
Does the checkbox properly enable / disable the tracking code?

#### Any background context you want to provide?
Needed for VCard ad campaign asap

#### Relevant tickets
Fixes #n/a

### CODE REVIEW

**Comment by angaither** [comment]
@deadlybutter can you add more context for what this does/why it's needed? there's no issue or sprint request for this?

**Comment by DFurnes** [comment]
Seems okay, but definitely would be nice to have an issue or ticket documenting this.

**Review by DFurnes — APPROVED** [review]

**Comment by madho** [comment]
We should try this!
<3 madho

**Comment by weerd** [comment]
@madho was re-added in a different fashion in #7545

**Pull request merged**
