### PR TITLE
Removes profile link conditional

### LINKED ISSUE #3260: Remove "User Profile Link" theme setting / conditionals
Cleanup task for once we're ready to go live with the Profile. We don't need the theme setting or the conditional logic in the template anymore.

### PR DESCRIPTION
**Pull request by itsjoekent**
Fixes #3260 

@aaronschachter 

screen shot 2014-12-17 at 1 59 14 pm

### CODE REVIEW

**Comment by aaronschachter** [comment]
We can't do this one until we have all issues in the milestone closed and signed off :frowning:

**Comment by itsjoekent** [comment]
oh yeah i forgot, oh well we can leave it open till its time

**Comment by aaronschachter** [comment]
You'll also want to delete the actual theme setting here: https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/theme-settings.php#L46

FYI, Theme settings are handled in the admin UI here: http://staging.beta.dosomething.org/admin/appearance/settings/paraneue_dosomething

**Comment by aaronschachter** [comment]
Comment above is still valid, this issue is to completely remove the checkbox / conditionals, simplifying our codebase such that the user profile is just always displayed.

**Comment by aaronschachter** [comment]
Still valid - just need to remove theme setting from `admin/appearance/settings/paraneue_dosomething`

**Comment by itsjoekent** [comment]
Replaced by https://github.com/DoSomething/dosomething/pull/4013

**Pull request closed without merging**
