### PR TITLE
Adding sshfs and add'l cpus for speed

### PR DESCRIPTION
**Pull request by blisteringherb**
- Loading the sshfs commands if the plugin is installed
- Adding an additional cpu and more memory to the box

Does this look like it makes sense?

@mshmsh5000 
@angaither

### CODE REVIEW

**Comment by angaither** [comment]
I mean, looks great to me. 
How do you set ENV variables?

**Comment by mshmsh5000** [comment]
This looks good to me, but doesn't make sense to merge until we automate some business with Salt: viz., copying the /vagrant director to an internal dir.

**Comment by mshmsh5000** [comment]
@blisteringherb I've upped the memory allocation in https://github.com/DoSomething/dosomething/pull/2390

But not the VCPU allocation. I also hard-coded the SSHFS mount point, because I think it might be too much to get devs to set env vars locally to make this work.

Thoughts?

**Comment by blisteringherb** [comment]
@mshmsh5000  Definitely makes sense.  Anything to make setting it up easier.

**Pull request closed without merging**
