### PR TITLE
Use bundled Ruby Sass to compile.

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
- Use bundled Ruby Sass to compile. :art:

### CODE REVIEW

**Comment by sergii-tkachenko** [comment]
:+1:

**Comment by sergiitk** [comment]
It changes the error from

```
Running "sass:prod" (sass) task
Warning:
You need to have Ruby and Sass installed and in your PATH for this task to work.
More info: https://github.com/gruntjs/grunt-contrib-sass
 Use --force to continue.
```

to

```
Running "sass:prod" (sass) task
Warning:
bundleExec options set but no Bundler executable found in your PATH.
More info: https://github.com/gruntjs/grunt-contrib-sass
 Use --force to continue.
```

**Comment by DFurnes** [comment]
Yep –– and Ruby Sass is actually a no-go because it requires 1.9.3 and we're stuck with 1.8.7 on the VM. I'm looking into jumping back to Libsass. Got everything compiling correctly with the latest Susy RC, but running into issues with the binary not compiling correctly on staging (Ubuntu).

**Comment by DFurnes** [comment]
So this PR is :-1: for now. For local dev, you can just compile things from your local machine if you have Ruby 1.9.3+ installed, and it should all be good. Sorry for the troubles.

**Pull request closed without merging**
