### PR TITLE
Signups endpoint

### LINKED ISSUE #6193: /signups index doesn't return data - breaking at an error message
#### Current Behavior

`/signups` index returns no data - breaking at `no reportback data found` and `no campaign data found` error messages. 

`https://thor.dosomething.org/api/v1/signups/23` returns 

```
{
  error: { 
    message: "No reportback data found."
  }
}
```

and `https://thor.dosomething.org/api/v1/signups/1` returns 

```
{
  error: {
    message: "No campaign data found."
  }
}
```
#### Desired Behavior

If the signup is not for a campaign, should not be included in the response. 
If there is no reportback, the reportback object should return `null` instead of the error message.

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?

Catches errors and returns null for campaigns and reportbacks in order to reach all /signup endpoints. 

For some reason, users can sign up for some nodes that are not `campaigns` or `sms_games` which was breaking when we tried to build the campaign in `Signup.php`'s `get` function. 

We were hitting the `No reportback found.` error, again breaking the endpoint, in the situation where there was a reportback in the database but couldn't be returned if has not yet been reviewed.
#### How should this be manually tested?

Make sure all `/signup` endpoints work and don't log and errors in the Drupal log messages. 

http://dev.dosomething.org:8888/api/v1/signups
http://dev.dosomething.org:8888/api/v1/signups/42
http://dev.dosomething.org:8888/api/v1/signups?user=98&campaigns=1227,1173
#### What are the relevant tickets?

Fixes #6193

### CODE REVIEW

**Comment by chloealee** [comment]
Ah yikes! @angaither do you know why it pulled other people's commits here?

**Comment by weerd** [comment]
Yeah, there's something crazy going on @_@

**Comment by weerd** [comment]
Try rebasing w/ dev....

**Comment by chloealee** [comment]
eek just did that and same thing! Maybe I should just close this and start over?

**Pull request closed without merging**
