### PR TITLE
Gets rid of all Rogue conditional flags since Rogue is always on

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?
- Gets rid of Rogue conditional logic because Rogue will never be turned off!

#### How should this be reviewed?
- Make sure all the logic is still working that you can: 
  - Signup
  - Reportback
  - Update quantity/why participated
  - Gallery is working
  - Gallery pagination is working
  - Kudos / reactions are working (and are persisted when you refresh the page) 
  - User profile page and is working and all data shows up as expected 
  - @sbsmith86 does anything with competitions need to be tested for this?
  - Did I miss anything? 

#### Relevant tickets
Fixes the issue in this [Pivotal Card](https://www.pivotaltracker.com/n/projects/2019429/stories/151415698).

#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love
- [ ] Post a message in #phoenix if this includes something that causes a rebuild!

### CODE REVIEW

**Review by DFurnes — APPROVED** [review]
This is so good!! 🔥 🔥 🔥

**Comment by chloealee** [comment]
yay thanks for the review, @DFurnes ! @sbsmith86 before I merge, just want to double check re: competitions work!

**Comment by DFurnes** [comment]
Yeah, competitions and signup data form are definitely the most "dangerous" changes. Are we currently using either of those on any legacy campaigns?

**Comment by chloealee** [comment]
@DFurnes asking around now to see! But for the signup data form, I tested that signups are working and all looked good on my local!

**Comment by chloealee** [comment]
Asked Ashely in [this thread ](https://dosomething.slack.com/archives/C02BBNZFA/p1508866641000183)and she said that we are no longer doing competitions for any legacy campaigns on ashes! So I think these changes should be safe then?

**Comment by sbsmith86** [comment]
@chloealee I'm good with killing storing competition info on phoenix-ashes. The only think I _could_ be concerned with is PN trying to find out if a user is in a competition or not, but they should be getting that from Gladiator and since there is nothing new happening in Gladiator this quarter we can probably kill it. 

As we look forward to Q4 we will probably handle competition signup information differently anyway.

**Comment by chloealee** [comment]
ok cool, thanks @sbsmith86 ! I'll merge this now :)

**Pull request merged**
