### PR TITLE
Fix extra header on user profile page.

### PR DESCRIPTION
**Pull request by DFurnes**
This took far too long to figure out...

### CODE REVIEW

**Comment by aaronschachter** [comment]
Not really needed for merge because it's more of a refactory question.. but is the fix here to create a page template without `$variables['header']` ?  Would it not make sense to take the header out of the user profile tpl and rework it to be displayed in the header variable?

**Comment by aaronschachter** [comment]
Brings up questions of where is the right place to put the header.

**Comment by barryclark** [comment]
:+1: 'ing to get this merged as we need to deploy soon. But let's talk more about @aaronschachter's thoughts above and also chat about the way we're implementing this header, etc.

**Comment by DFurnes** [comment]
@aaronschachter Yep, 100%. Just quicker than trying to get that variable accessible outside.

**Comment by aaronschachter** [comment]
Ok, sweet. let's create an issue to not forget about it though.

**Pull request merged**
