### PR TITLE
Changes the onboarding next functionality

### PR DESCRIPTION
**Pull request by itsjoekent**
#### What's this PR do?

If you reach the last slide we ask a user to finish instead of displaying a disabled button
#### How should this be reviewed?

Reach the last slide, does it ask you to finish?
#### Any background context you want to provide?

no
#### Relevant tickets

Fixes #not sure if the issue is made / ready yet

### CODE REVIEW

**Comment by weerd** [comment]
Can you fix the merge conflict before review?

**Comment by itsjoekent** [comment]
Well thats new...

**Comment by itsjoekent** [comment]
sorry about that @weerd , merge conflict fixed!

**Comment by weerd** [comment]
No worries! Re-:eyes:

**Review by weerd — APPROVED** [review]
👍

**Pull request merged**
