### PR TITLE
added feature modifier to the mosiac galleries in campaign grouped template

### PR DESCRIPTION
**Pull request by tjrosario**
Galleries on campaigned grouped pages to use the 'featured' modifer 

Fixes [DS-316](https://jira.dosomething.org/browse/DS-316)

### CODE REVIEW

**Comment by weerd** [comment]
Just to clarify, this isn't for **triad** galleries right? Even though it says that in the title for the PR?

**Comment by tjrosario** [comment]
Good catch.  Updated the title.

**Comment by weerd** [comment]
Looks fine though :) Glad it worked easily without much hassle!  :+1:

**Comment by DFurnes** [comment]
Can you update the commit message as well?

``` sh
git commit --amend
git push --set-upstream origin campaign-grouped-galleries --force
```

**Comment by tjrosario** [comment]
@DFurnes all set

**Comment by DFurnes** [comment]
Great! :thumbsup:

**Pull request merged**
