### PR TITLE
Remove unused text format module/libs

### LINKED ISSUE #573: Remove CKEditor library
I assume this is not necessary, given that we're going to use Markdown across the board:

https://github.com/DoSomething/dosomething/commit/7e4b3b2b

Can we just revert? @desmondmorris since this was your commit, please comment then reassign.

### LINKED ISSUE #584: Remove WYSIWYG Module

### PR DESCRIPTION
**Pull request by angaither**
Fixes #584
Fixes #573

### CODE REVIEW

**Comment by aaronschachter** [comment]
Need to also remove modules from the dosomething.info file.

**Comment by angaither** [comment]
@aaronschachter updated

**Comment by aaronschachter** [comment]
:+1: Looks good.  How will this work with staging though?  Would we manually just disable the modules and delete the directories in html/profiles/dosomething/modules/contrib ? cc: @mshmsh5000 @desmondmorris

**Comment by angaither** [comment]
drush-make would fix this, right? 
we need something a little like this when we deploy 
https://github.com/letharion/Drupal-build-scripts/blob/master/build.sh

**Comment by aaronschachter** [comment]
yes, and yes

**Pull request merged**
