### PR TITLE
adds 404 error code when error is thrown in campaign.php, signup.php,…

### LINKED ISSUE #6261: API individual resources should return error code 404 when not found
#### Current Behavior
- Requesting a non existing campaign from the `campaigns/:id` endpoint results in a 200 with an `error` object.
#### Desired Behavior
- A 404 response should be returned
#### Why This Matters

It's RESTful best practice :stars: and makes it easier to build apps with our API.  This is not critical for app launch as we have a [workaround for this in the iOS repo](https://github.com/DoSomething/LetsDoThis-iOS/blob/d8f8c406465caa13f8b1e4cdd2d883125307b960/Lets%20Do%20This/Networking/DSOAPI.m#L271), but would be nice to remove the hack post-v1.1.0
#### Relevant Screenshots + Links

Refs https://github.com/DoSomething/phoenix/issues/6163#issuecomment-195054295
screen shot 2016-03-10 at 1 16 49 pm
_

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?

Adds `404` response code when no campaign, signup, or kudos data is found. 
#### How should this be manually tested?

Hit any of the below endpoints to make sure the status code if a `404 Not Found`
#### What are the relevant tickets?

Fixes #6261 

… and kudos.php

### CODE REVIEW

**Comment by DFurnes** [comment]
Hmm, it'd be nice if this logic could be shared between all the different model classes.

**Comment by chloealee** [comment]
@DFurnes do you mean create a function for this in the entityreference.module file (which I assume is the file that `extends Entity` references?)?

**Comment by DFurnes** [comment]
I think it could make sense to add a base `Model` class that each of these inherits from, but that can definitely be saved as a refactoring task somewhere down the road.

**Comment by DFurnes** [comment]
Oh, I see. Interesting! `Kudos` and `Signup` extend from `Entity` but `Campaign` doesn't. Either way, that's out-of-bounds since it's a Dr00ps built-in so no biggie for this PR. :smile: 

/cc @weerd

**Comment by chloealee** [comment]
ah thanks, @DFurnes ! Definitely a good practice to think about extracting to make it DRY :)

**Comment by angaither** [comment]
:+1:

**Comment by weerd** [comment]
post-merge :+1:

**Pull request merged**
