### PR TITLE
Adding missing term to POT file.

### PR DESCRIPTION
**Pull request by weerd**
Refs #5517
#### What's this PR do?

This PR adds a missing term to the **dosomething_campaign.pot** file and also ensures the associated term is wrapped in the `t()` function wherever it is output.
#### Where should the reviewer start?

Take a quick :eyes: 
#### How should this be manually tested?

Will be tested on Thor.
#### What are the relevant tickets?
#5517

---

@angaither

### CODE REVIEW

**Comment by angaither** [comment]
there's no `t('snap a pic');` here!

**Comment by weerd** [comment]
cause it's already wrapped. but the POTx module never pulled it for some reason...

https://github.com/DoSomething/phoenix/blob/860b7b8c1a7382cdf136bd1547fc7708e3eca66a/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.module#L16

**Comment by angaither** [comment]
I thought you were trying to pull the :sheep: over my :eyes:!

**Comment by angaither** [comment]
:+1:

**Comment by weerd** [comment]
haha

**Pull request merged**
