### PR TITLE
Update hot module timing logic.

### PR DESCRIPTION
**Pull request by angaither**
Instead of calculating the time a bunch, just set it to vars array on the node.

refs #5907

### CODE REVIEW

**Comment by sbsmith86** [comment]
:+1: :watch:

**Comment by aaronschachter** [comment]
This seems to have broken things on staging:

screen shot 2015-12-07 at 5 05 00 pm

**Comment by angaither** [comment]
hmm @aaronschachter strange that you aren't getting taken to `/us`

I think it's just an issue with not having translations on staging, but I'll look into this

**Comment by aaronschachter** [comment]
FYI - `staging.dosomething.org` directs me to /`us`, but `staging.beta.dosomething.org` does not. Will purge browser history to stop visiting it. We've already made the changes in the LDT iOS app to point to `staging.dosomething.org/api`

**Comment by mikefantini** [comment]
@aaronschachter staging.dosomething.org is behind Fastly whereas staging.beta.dosomething.org is not. This is why staging.dosomething.org directs you to /us but staging.beta does not.

**Pull request merged**
