### PR TITLE
Fixes quantity spelling error

### LINKED ISSUE #4468: Update sum_rb_quanity -> sum_rb_quantity
write an update hook to update the spelling and change it where used
places used: 
- [x] dosomething_reportback.cron.inc
- [ ] dosomething_campagin.theme.inc
- [x] dosomething_helpers.variable.inc

### PR DESCRIPTION
**Pull request by itsjoekent**
Fixes #4468 

@angaither

### CODE REVIEW

**Comment by angaither** [comment]
@deadlybutter this is also already in use in production, so you'll need to write an update hook that changes the ones that are currently set

**Comment by itsjoekent** [comment]
do I keep these changes then or does the hook take care of them?

**Comment by angaither** [comment]
both! update hook & these changes!

**Comment by itsjoekent** [comment]
@angaither install hook added

**Comment by angaither** [comment]
:+1:

**Pull request merged**
