### PR TITLE
Cross browser mods

### PR DESCRIPTION
**Pull request by tjrosario**
Adds fallback for nth-child hooks in IE8

### CODE REVIEW

**Comment by DFurnes** [comment]
Looks good. Does `dosomething_helpers_get_gallery_item_order_class` belong in the theme though, since it's only view related?

**Comment by weerd** [comment]
Cool. Now I understand what you meant earlier :)

**Comment by tjrosario** [comment]
@DFurnes it was moved out of theme into helpers as it is used by static_content and campaign_run now.

**Comment by weerd** [comment]
:+1:

**Comment by DFurnes** [comment]
Even if it's used by multiple modules, it's a theme-related concern. It only makes sense in the context of the Paraneue theme and the markup we're using there. Modules should be holding business logic - if you look at the majority of the other functions in the `dosomething_helpers.module` file, that's what they are.

It's not a blocker, just something worth considering and potentially re-organizing later.

**Comment by tjrosario** [comment]
@DFurnes Noted. Is there a best practice you are using for shared theme-specific methods?

**Comment by DFurnes** [comment]
It looks like we've been putting things like this in [dosomething_helpers.theme.inc](https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_helpers/dosomething_helpers.theme.inc) so far. I'd argue that [helpers.inc](https://github.com/DoSomething/dosomething/blob/dev/lib/themes/dosomething/paraneue_dosomething/includes/helpers.inc) in the theme would be the best place for template helper functions like this since they're being used to generate theme-specific markup.

Definitely willing to hear other arguments though... I'm just worried that `dosomething_helpers` seems to be becoming a dumping ground.

/cc @aaronschachter @angaither Any thoughts?

**Comment by aaronschachter** [comment]
I agree on all points, @DFurnes . Moving this function in particular into a theme `helpers.inc` sounds good here.

**Comment by DFurnes** [comment]
Cool, made a low priority issue so we don't forget about it. :thumbsup:

**Comment by tjrosario** [comment]
Great!

**Pull request merged**
