### PR TITLE
Update to use medium sized button for signups and some style adjustments...

### LINKED ISSUE #2105: [Campaign] Adjust  "Submit" button size on Pitch page
Maybe switch from large to medium?

screen shot 2014-05-13 at 3 25 48 pm

### PR DESCRIPTION
**Pull request by weerd**
Resolves #2105

@DFurnes && @aaronschachter

### CODE REVIEW

**Comment by DFurnes** [comment]
:sunflower:

**Comment by weerd** [comment]
:sunny:

**Comment by aaronschachter** [comment]
Looks fine. I'd like to refactor the adding of classes into the `signup_form` into somewhere in the `template.php` or relevant files in theme, but this is works fine for now :+1:

**Comment by weerd** [comment]
Agreed. Ideally we could add them in the template, so it's more context based, but I know that might be a bit more difficult, especially with Drupal forms.

**Pull request merged**
