### PR TITLE
Added a pre-commit hook to check for common mistakes.

### PR DESCRIPTION
**Pull request by angaither**
## What does this PR do?
- adds in pre-commit hooks that fire before committing
- adds the symlinked git hook into the `ds build` task
## What are we checking for?
- git conflicts to be committed
- drupal debug code (`dsm`, `dpm`, `krumo`)
## How do I test this?
- pull down this code
- add some `dpm`s
- `git commit`
- you will see this error

```
Error: git pre-commit hook forbids committing "dpm" to hooks/pre-commit
--------------
To commit anyway, use --no-verify
```

The code was generously provided by [this man](https://github.com/bobgilmore/githooks)

### CODE REVIEW

**Comment by aaronschachter** [comment]
Do you need to rebuild?  I've pulled down and testing from my `dosomething-mount` but able to commit with `dpm`'s in my code...

This also looks interesting, as far as running Coder in pre-commit-hook https://www.drupal.org/node/2054259#comment-7970545

**Comment by aaronschachter** [comment]
Ran `ds symlinks` . but still able to commit `dsm`s...

**Comment by angaither** [comment]
From inside `dosomething-mount` 
if you run `ls .git/hooks/` does 'pre-commit' show up?
if not it means the symlinks didn't work.
Make sure to run bin/ds symlinks inside of `/var/www/vagrant` then you should see the pre-commit file and it will give you the warning before committing a `dsm`

**Comment by aaronschachter** [comment]
Ah, the trick was I ran `ds symlinks` and not `bin/ds symlinks`.  Why is there a difference?  If you run just `ds symlinks` the `Add git pre-commit hook` does not appear.

What are the steps to get everyone to do this? Does everyone need to run `bin/ds symlinks` or will it happen upon a new `ds build` ?  Code looks good :+1: just need clear steps for how to get this working for everyone.

**Comment by angaither** [comment]
It'll happen once people do a `ds build` or manually run `bin/ds symlinks`

**Comment by aaronschachter** [comment]
Not a biggie but FYI when I run `ds pull stage`, I get this output:

```
Linking modules
Linking themes
Add git pre-commit hook
ln: failed to create symbolic link `.git/hooks/pre-commit': No such file or directory
```

Ds pull stage calls `ds symlinks` to recreate the sylinks once files are pulled down from stage.

**Comment by angaither** [comment]
Ah, ew okay, I can add it in at a different point, or just have people manually add the symlink, since it only needs to happen one time. Thoughts?

**Comment by aaronschachter** [comment]
Hmm, I wonder if this is could be a reason that pulling files from stage seems to be taking longer. Maybe we add it once in `ds build` but keep it out of `ds symlinks`?  Or check if the symlink exists before creating?

**Pull request merged**
