### PR TITLE
Campaign content endpoint

### LINKED ISSUE #2711: Install and configure Services module
- [x] Add Services to the DS profile
- [x] Add and export an endpoint, perhaps `api/v1`. Only enable node retrieve (GET)
- [x] Implement `hook_services_request_postprocess_alter` to customize node GET output:
  - [x] If a campaign --  Campaign class provided by `dosomething_campaign_load` when viewing a campaign node
  - [x] If not a campaign -- don't return any content for now.  Only endpoint to return campaigns (this is our only use case so far)

### PR DESCRIPTION
**Pull request by aaronschachter**
Resolves #2711 by adding, enabling, and configuring / postprocessing Services contrib module.

Request:

```
curl http://dev.dosomething.org:8888/api/v1/content/1199  -H "Content-type: application/json" --header "Accept: application/json"
```

Response:

```
{
    "nid": "1199",
    "title": "SMS Game Fun Great Success",
    "status": "active",
    "type": "sms_game",
    "call_to_action": "Challenge friends to stand up to bullying on their phones.",
    "solution_support": "Sandwiches help self esteem and hunger.",
    "starter_statement_header": "I say hey hey hey whats going on",
    "items_needed": null,
    "promoting_tips": null,
    "solution_copy": "<p>Text BULLY to 38383 and then eat a sandwich!</p>\n",
    "starter_statement": "<p>This is a starter statement that appears below the Section 2.</p>\n",
    "time_and_place": null,
    "vips": null,
    "primary_cause": null,
    "high_season_start": null,
    "high_season_end": null,
    "low_season_start": null,
    "low_season_end": null,
    "fact_problem": {
        "fact": "1 in 4 teachers see nothing wrong with bullying and will only intervene 4% of the time.\r\n",
        "nid": "97",
        "footnotes": "1",
        "sources": ["<p>Cohn, Andrea, and Andrea Canter, Ph.D. \"Bullying: Facts for Schools and Parents.\" NASP Fact Sheet. Accessed February 9, 2014, http://www.nasponline.org/resources/factsheets/bullying_fs.aspx.</p>;\n"]
    },
    "fact_solution": null,
    "fact_sources": ["<p>Cohn, Andrea, and Andrea Canter, Ph.D. \"Bullying: Facts for Schools and Parents.\" NASP Fact Sheet. Accessed February 9, 2014, http://www.nasponline.org/resources/factsheets/bullying_fs.aspx.</p>;\n"],
    "faq": [{
        "header": "Where do we go from here?",
        "copy": "<p>The words are coming out all weird, where are you now, when I need you.</p>\n"
    }, {
        "header": "Who is the best Ninja Turtle?",
        "copy": "<p>The answer is Raphael.</p>\n"
    }],
    "step_pre": null,
    "step_post": null,
    "variables": [],
    "image_cover": {
        "nid": 1193,
        "is_dark_image": 1
    },
    "image_header": {
        "nid": 1193,
        "is_dark_image": 1
    }
}
```

### CODE REVIEW

**Comment by deezone** [comment]
With:

```
      $campaignApiUrl = getenv('DS_CAMPAIGN_API_HOST') . ':' . getenv('DS_CAMPAIGN_API_PORT') . '/api/v1/content/' . $targetCampaign->nid;
      curl_setopt($ch, CURLOPT_URL, $campaignApiUrl);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt($ch, CURLOPT_HTTPHEADER, array(
       'Content-Type: application/json',
       'Accept: application/json',
));  
      $jsonResult = curl_exec($ch);
      $result = json_decode($jsonResult);
```

Tried the following based on `README.md`:

```
https://www.dosomething.org:8888/api/v1/content/2132
```

returned "0"
AND 
based on comment above:

```
curl http://dev.dosomething.org:8888/api/v1/content/1199  -H "Content-type: application/json" --header "Accept: application/json"
```

Tried:

```
http://dev.dosomething.org:8888/api/v1/content/2132
```

return 404 page contents.
- Tried from command line:

```
curl http://dev.dosomething.org:8888/api/v1/content/1199  -H "Content-type: application/json" --header "Accept: application/json"
```

Returns 404 page contents.

Suggestions?

**Comment by aaronschachter** [comment]
First double check that you have the latest code...

It sounds like Services / Rest Server is not enabled: `drush -y en services rest_server` then `drush -y fra` to get the `drupalapi` endpoint defined in `dosomething_settings`.

Or, can just pull down from stage db.  (Or run `ds build` locally)

**Comment by deezone** [comment]
I pulled down a copy of the stage db at end of the day yesterday.  I'll try your advice in getting the service running locally.

Can I assume this is not running on the production server yet? Thus the failed attempt to hit:

```
https://www.dosomething.org:8888/api/v1/content/2132
```

**Comment by aaronschachter** [comment]
It should be running once we deploy today.

**Comment by deezone** [comment]
Sweet!

**Comment by aaronschachter** [comment]
Did you get it working locally using stage db?

**Pull request merged**
