### PR TITLE
Removes transactional_user_profile_update MB production.

### LINKED ISSUE #4025: Remove transactional_user_profile_update production from dosomething_mbp installation
As discussed with @DeeZone, this production is not used anymore.

### PR DESCRIPTION
**Pull request by sergiitk**
Closes #4025.

### CODE REVIEW

**Comment by deezone** [comment]
This is a product of the idea to use Drupal user profiles maintain their email subscription preferences. This feature has been deferred for a stand alone solution: https://github.com/DoSomething/mbc-user-subscriptions which is in the final stages of development. All related Drupal issues should be closed.

**Comment by sergiitk** [comment]
@DeeZone But shouldn't we cleanup Drupal code?

**Comment by deezone** [comment]
Very good point, I'll take care of getting the production out of the code base as it's no longer needed.

**Comment by deezone** [comment]
Related: https://github.com/DoSomething/dosomething/pull/4028

**Comment by deezone** [comment]
:+1:

**Pull request merged**
