### PR TITLE
Fixes #1092, 11 Facts: Remove sources.

### LINKED ISSUE #1092: 11 Facts: Remove sources

### PR DESCRIPTION
**Pull request by weerd**
Not sure if my method of commenting out the template code follows the correct standard. If not, let me know and I'll fix it!

### CODE REVIEW

**Comment by aaronschachter** [comment]
I probably would have gone with 

```
<?php /*
stuff stuff
stuff
*/ ?>
```

but this works fine.  Happy first PR! :+1: ship it value added

**Comment by weerd** [comment]
Yeah. True. Just used to highlighting and hitting Command + / in sublime text to comment anything out ;)

**Comment by DFurnes** [comment]
Acceptable! :hammer:

**Comment by weerd** [comment]
Why is it :hammer: and not :gavel: ?

**Pull request merged**
