### PR TITLE
Updating the triad gallery with new markup and styles.

### LINKED ISSUE #2034: [Grouped Campaigns] Link / modalize Zendesk form
Depends on #2033

### LINKED ISSUE #2130: [Grouped Campaigns] Markup and style general gallery

### PR DESCRIPTION
**Pull request by weerd**
Updated the triad gallery and also modalized the ZendDesk contact us form.

@DFurnes @aaronschachter 

Resolves #2130 
Resolves #2034 

*forgot to add above resolves issue number.

### CODE REVIEW

**Comment by aaronschachter** [comment]
this looks good except the content type is not configured to use a signup data form. would prefer to remove this code (I see it's commented out) until there is a need for it.

**Comment by weerd** [comment]
I think I just forgot to remove it. I had it commented out cause I was going to replace it, but was tired and forgot to delete. Will delete!

**Comment by weerd** [comment]
@aaronschachter I updated it! Commented out code removed.

**Comment by aaronschachter** [comment]
:+1: sweet, ship it

**Pull request merged**
