### PR TITLE
Fixing scoping issue, adding semicolon after function declaration.

### PR DESCRIPTION
**Pull request by sbsmith86**
Fixing some small bugs I found when compiling JS. @weerd @DFurnes

### CODE REVIEW

**Comment by DFurnes** [comment]
:+1:

**Comment by weerd** [comment]
So it was scoping to the parent object instead of the submit element?

**Comment by weerd** [comment]
:+1:

**Comment by sbsmith86** [comment]
@weerd `_this` wasn't defined in the `enableSubmit()` function and didn't need to be. I could use the global context of `this`

**Comment by weerd** [comment]
Ah, gotcha :) Good catch!

**Pull request merged**
