### PR TITLE
Makes taxonomy terms translatable

### LINKED ISSUE #5715: Make taxonomy collections translatable
The ideal scenario is that we keep all US users on /us/ throughout their entire experience. In order to do this we need to make Taxonomy Collections translatable.

refs: #5710

### LINKED ISSUE #5758: Translatable fields are missing from Taxonomy Terms
Missing cover image and facts:
https://thor.dosomething.org/taxonomy/term/13/edit -> https://thor.dosomething.org/volunteer/bullying
https://thor.dosomething.org/taxonomy/term/16/edit -> https://thor.dosomething.org/volunteer/animals

### PR DESCRIPTION
**Pull request by sergiitk**
#### What's this PR do?
- Updates dosomething_taxonomy feature so it's not overridden
- Saves entity translation type settings
- Enables taxonomy translation
- Saves default taxonomy vocabularies translation settings
- Configures Taxonomy Vocabularies translation
- Moves up taxonomies language field to the top after Name field
- Replaces Taxonomy Name and Description with translatable fields
- Provides a tool to fix taxonomy term fields replaced by title module
- Provides `ds-global` routine to fix taxonomy translatable fields
- Enables translation of taxonomy's field_title
- Fixes taxonomy's field_title translations
#### How should this be manually tested?
- Download branch
- Import Prod database
- Run `ds-global make-taxonomy-translatable`
- Go to http://dev.dosomething.org:8888/us/taxonomy/term/1/edit, check all fields are present
- Click Save / View
- Translate term, check that translation is viewable
#### Any background context you want to provide?

@angaither @deadlybutter: Default language for taxonomies need to be set to 'English', because term entity doesn't have actual language column and it's language is determined only in Entity Translation tables. Should we alter the language on creation for regional admins?

@deadlybutter Do we need any specific redirects for taxonomies, as we made for nodes?

@mikefantini @sheyd  Taxonomy Translation Matrix: https://docs.google.com/spreadsheets/d/1nYdrVRh67dpRvr7CmGXNeKUWY0PkbqgnS3pPqDRzFqc/edit#gid=0&vpid=A2
#### What are the relevant tickets?
- Fixes #5758 
- Closes #5715
## 

CC @sheyd @mikefantini @deadlybutter

### CODE REVIEW

**Comment by itsjoekent** [comment]
I'm not sure what the behavior for taxonomy is supposed to be, but I think it could probably integrate with the existing logic without much trouble. 

I'm not sure if it needs anything special but I assume so.

**Comment by sergiitk** [comment]
@deadlybutter #5715 might clarify how we want it to work.

**Comment by sheyd** [comment]
@sergii-tkachenko :100: and :+1: for the Translation Matrix!

**Comment by angaither** [comment]
@sergii-tkachenko rebase to get the style ci changes to pass!

**Comment by sergiitk** [comment]
Thanks for the suggestion, @angaither!

**Comment by angaither** [comment]
@sergii-tkachenko looks :ok: we might want to version our current branch before this merge into dev, to get the reportback stuff in a different version

**Comment by angaither** [comment]
as you can see in #deploys i have been unsuccessful at that

**Comment by sergiitk** [comment]
Fixer script executed on production:

```
dosomething@ip-10-100-35-14:/var/www/www.dosomething.org/current$ ds-global make-taxonomy-translatable
     ___           ___       ___           ___           ___           ___
    /\  \         /\__\     /\  \         /\  \         /\  \         /\__\
   /::\  \       /:/  /    /::\  \       /::\  \       /::\  \       /:/  /
  /:/\:\  \     /:/  /    /:/\:\  \     /:/\:\  \     /:/\:\  \     /:/  /
 /:/  \:\  \   /:/  /    /:/  \:\  \   /::\~\:\__\   /::\~\:\  \   /:/  /
/:/__/_\:\__\ /:/__/    /:/__/ \:\__\ /:/\:\ \:|__| /:/\:\ \:\__\ /:/__/
\:\  /\ \/__/ \:\  \    \:\  \ /:/  / \:\~\:\/:/  / \/__\:\/:/  / \:\  \
 \:\ \:\__\    \:\  \    \:\  /:/  /   \:\ \::/  /       \::/  /   \:\  \
  \:\/:/  /     \:\  \    \:\/:/  /     \:\/:/  /        /:/  /     \:\  \
   \::/  /       \:\__\    \::/  /       \::/__/        /:/  /       \:\__\
    \/__/         \/__/     \/__/         ~~            \/__/         \/__/

Replacing field values for name in action_type taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for description in action_type taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for name in cause taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for description in cause taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for name in image_tags taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for description in image_tags taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for name in issue taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for description in issue taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for name in kudos taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for description in kudos taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for name in partners taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for description in partners taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for name in tags taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for description in tags taxonomy_term.
Done.                                                                                                                                                                                                                                                                [ok]
Replacing field values for field_title.
Data successfully processed.                                                                                                                                                                                                                                         [status]
```

**Pull request merged**
