### PR TITLE
Fixing Reportback endpoints after Northstar changes.

### LINKED ISSUE #6083: /reportbacks & /reportback-items user data broken
While working on campaign runs and checking Runscope, user data retrieval for the `/reportbacks` and `/reportback-items` endpoints is broken. Turns out the recent upgrades made to Northstar response structure changed the structure Phoenix was expecting, and thus was breaking the Phoenix user retrieval methods.

---

cc: @DFurnes @jonuy

### PR DESCRIPTION
**Pull request by weerd**
Fixes #6083
#### What's this PR do?

Recent upgrades to Northstar inadvertently broke the Phoenix API when including users. This should fix the issue.
#### Where should the reviewer start?

Just double check the two classes and the Transformer.
#### What are the relevant tickets?
#6083

---

@DFurnes 

cc: @jonuy @angaither @chloealee

### CODE REVIEW

**Comment by DFurnes** [comment]
Whoops, :shirt:!

**Edit:** err, :shipit:! Autocorrect...

**Comment by weerd** [comment]
@DFurnes The `id` is preferred over `_id` correct?

**Comment by DFurnes** [comment]
Yeah, that's something I added in when I made the transformers in Northstar. I think it's cleaner, since it abstracts away the database-backend stuff (so we could have an ID that didn't necessarily map to a Mongo object somewhere down the line).

**Comment by weerd** [comment]
Cool cool. Yeah, that's what I suspected, but wanted to confirm :)

**Pull request merged**
