### PR TITLE
Removes profile link conditional

### LINKED ISSUE #3260: Remove "User Profile Link" theme setting / conditionals
Cleanup task for once we're ready to go live with the Profile. We don't need the theme setting or the conditional logic in the template anymore.

### PR DESCRIPTION
**Pull request by itsjoekent**
Fixes #3260 

@aaronschachter

### CODE REVIEW

**Comment by aaronschachter** [comment]
Looks good, just need to also remove the "User Profile" theme setting in the Paraneue theme settings form.

**Comment by itsjoekent** [comment]
GAH that commit wont go away. Dont merge yet

**Comment by aaronschachter** [comment]
what commit?

**Comment by itsjoekent** [comment]
ignore, I got rid of it the cheaty way

**Comment by aaronschachter** [comment]
:+1:

**Comment by itsjoekent** [comment]
:zap:

**Pull request merged**
