### PR TITLE
No more first names

### LINKED ISSUE #5157: Remove first name fields from SMS game form
The first name fields tested in #4247 and implemented in #4710 are unfortunately being reverted! :fire: Although they increased completion rate for games, they decreased conversion rates significantly. Therefore, we're going to remove those fields and return styles to how they were previously.

/cc @mikefantini @namimody

### PR DESCRIPTION
**Pull request by DFurnes**
### Changes

Closes #5157. This removes first name fields from the multiplayer SMS game form & associated styles and validation rules, since we are [no longer interested in collecting them](https://cloud.githubusercontent.com/assets/583202/9967116/9e000cfc-5e0e-11e5-8cae-a81529349475.png).
### How should I test this?

Feel free to pull down to your local and test, although changes should be fairly easy to follow... (it's basically just removing conditional logic that was added in the two referenced PRs).
### Screenshots

The SMS game form (configured for a multiplayer game) on staging:
screen shot 2015-09-18 at 1 56 57 pm

The SMS game form (configured for a multiplayer game) on this branch:
screen shot 2015-09-18 at 1 57 25 pm

---

@DoSomething/front-end

### CODE REVIEW

**Comment by itsjoekent** [comment]
does this mean we get to actually call your furn-z now?

**Comment by weerd** [comment]
Furnes, Furnes. <--- full name (last, first)

**Comment by itsjoekent** [comment]
:+1:

**Comment by weerd** [comment]
:+1:  FURNES

**Comment by itsjoekent** [comment]
dancing

**Pull request merged**
