### PR TITLE
404 path copy size

### PR DESCRIPTION
**Pull request by sbsmith86**
Changing the width of the text on path specific pages. 

/cc @DFurnes @barryclark

### CODE REVIEW

**Comment by DFurnes** [comment]
Seems good to me! :boat:

**Comment by DFurnes** [comment]
Oh, can you add a `@TODO` to remind us we need to go back and fix this once we refactor typography?

**Comment by sbsmith86** [comment]
@DFurnes thanks! and will do.

**Comment by weerd** [comment]
Yeah, looks good to me too :) :+1:

**Pull request merged**
