### PR TITLE
Vagrant: add access to RabbitMQ admin.

### PR DESCRIPTION
**Pull request by sergiitk**
See http://dev.dosomething.org:15672:
image

cc @DeeZone

### CODE REVIEW

**Comment by angaither** [comment]
woah

**Comment by itsjoekent** [comment]
:mindblown:

**Comment by sergiitk** [comment]
It already was sitting there for a while :)

**Comment by deezone** [comment]
`15672` is the RabbitMQ Management Plugin port. The UI as well as API calls go through the same port. Pointing to `/admin/config/services/message-broker-producer` should also work as it gets Rabbit health stats via this port.

Nice :+1:

**Pull request merged**
