### PR TITLE
Adds gladiator key header

### LINKED ISSUE #6300: Include api key in gladiator calls
Add api key to gladiator settings form
and to all requests
DoSomething/gladiator/issues/69

### PR DESCRIPTION
**Pull request by itsjoekent**
#### What's this PR do?

Adds gladiator key and header 
#### How should this be manually tested?

Can it make requests to gladiator?
#### Any background context you want to provide?

no
#### What are the relevant tickets?

Fixes #6300

### CODE REVIEW

**Comment by itsjoekent** [comment]
waiting for https://github.com/DoSomething/gladiator/pull/129#discussion_r57044486 to be merged so i can test this works

**Comment by angaither** [comment]
@deadlybutter please add these values to the [config form](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_gladiator/dosomething_gladiator.admin.inc) as well

**Comment by itsjoekent** [comment]
@angaither i think this is ready!

**Comment by angaither** [comment]
:+1:

**Pull request merged**
