### PR TITLE
DS API: Get Member Count

### PR DESCRIPTION
**Pull request by aaronschachter**
Closes https://jira.dosomething.org/browse/DS-444

Provides an endpoint to get the Member Count.  Must use POST, as its a custom Services resource action.  Will update wiki upon merge.

**POST** http://dev.dosomething.org:8888/api/v1/users/get_member_count.json

Result:

```
    {
       "formatted": "2,900,343",
       "readable": "2.9 million"
    }
```

### CODE REVIEW

**Comment by angaither** [comment]
:+1: 
how/where does the number get set? (or pulled from)

**Comment by DFurnes** [comment]
Coooooool.

**Comment by aaronschachter** [comment]
@angaither -- It's a Drupal variable. @deadlybutter is working on a MemberCounter app that sets the variable via the Drupal app's Services `set_variable` resource.  The DS User admin form also has this variable is exposed, in case we ever need to override it.

**Comment by angaither** [comment]
@aaronschachter sweet!

**Pull request merged**
