### PR TITLE
Member Support, User Search

### LINKED ISSUE #1428: Member support role
Needs ability to edit user accounts.

### LINKED ISSUE #1429: User search view
Create a view with exposed filters to allow searching by
- UID
- Email
- Mobile

Which links to the user profile.

Grant access to staff.

### PR DESCRIPTION
**Pull request by aaronschachter**
- Fixes #1428 -- new role `member support` can access admin theme, menu and most importantly: administer users.
- Fixes #1429 -- creates `user_search` view at path `/admin/members`.  Query users by uid, email, or mobile and visible to users with "access administration menu" permission granted.

I have no idea why `features-update` is removing so many dependencies in `dosomething.info`, but I like it.  The only change I can think of is the change in #809... but this shouldn't hurt anything by not requiring these modules as dependencies, as we're only defining permissions..

### CODE REVIEW

**Comment by aaronschachter** [comment]
Still in progress: Making updates so that member support can view any reportback, and also just change the view name to "Users" instead of "Members".

**Comment by aaronschachter** [comment]
PR is updated and ready for review. Member Support role can administer users, and view any signup or reportback.

**Comment by angaither** [comment]
As long as this doesn't break ds build since modules are turned on from the info file.

**Comment by aaronschachter** [comment]
Oh, I typed the wrong thing. Dependences are being removed from `dosomething_user.info` not `dosomething.info`.

**Comment by angaither** [comment]
:+1:

**Pull request merged**
