### PR TITLE
Adds Signup/Reportback objects as properties to Campaigns class

### PR DESCRIPTION
**Pull request by aaronschachter**
screen shot 2015-03-06 at 7 44 45 am

### CODE REVIEW

**Comment by angaither** [comment]
@aaronschachter is there an issue for this?
this just returns data for the current user?

**Comment by aaronschachter** [comment]
Yup, the issue is referenced in the commit message (https://github.com/DoSomething/dosomething/issues/4119) -- and yes, just interested in current user's activity.

**Comment by angaither** [comment]
:+1: code looks ok
but I'm just very confused why this endpoint would return this data, shouldn't it be it's own endpoint?
calling for a node should return the node data, not user data.... and if it is returning user data, it should be requested in the url, not just the current user

**Comment by aaronschachter** [comment]
Definitely open to suggestions / convo about this but the logic behind this is that anytime a user is viewing a Campaign, we need to know both if they are signed up for it and if they reported back.  We do this while viewing a Campaign on the web as well. I suppose apps which use the API could be make 3 separate GET requests, but that's 3 GET's per Campaign View.. and just seems like unnecessary steps if they could be returned in one shot...

**Comment by sergiitk** [comment]
I agree with @angaither. It is strange to see current user's data returned by the endpoint correspondent to content management. I'd suggest to create `/users/current/*` endpoints for exposing current user related information.

**Comment by aaronschachter** [comment]
But each signup and reportback is node specific, so what would those URL's look like @sergii-tkachenko  ?

**Comment by sergiitk** [comment]
Something like `/users/current/campaign/1918.json`. This can return information user specific info for campaign id 1918, such as reportbacks and signups.

**Comment by aaronschachter** [comment]
@sergii-tkachenko @angaither  I think the `current` is throwing me off here, because we will eventually start having Signups and Reportbacks for Campaign Run nodes.

Maybe lose the `current` for something like `users/activity?nid=362` ? 

Where the nid can be a Campaign, or a Campaign Run...

**Comment by angaither** [comment]
That sounds good @aaronschachter 
Also, isn't the idea that the user api should be handling this anyways?

**Comment by sergiitk** [comment]
@aaronschachter yes, sounds great!

**Comment by aaronschachter** [comment]
Ok, I'll close this and open a new one. @angaither I believe storing signups/reportbacks in User API is the end goal but building this into Drupal for now to unblock mobile app development.

**Comment by angaither** [comment]
yeah, the only thing blocking this in northstar the fact that there aren't users in the api.
But it's currently storing signups/reportbacks

**Comment by aaronschachter** [comment]
Ohh @sergii-tkachenko I get the `current` now. So it would be

`users/current/activity?nid=362`
and 
`users/328342/activity?nid=362`

**Comment by sergiitk** [comment]
:dancer: Yes!

**Comment by aaronschachter** [comment]
This reminds me of how it'd be pretty nice to refactor Signups and Reportbacks into one "Activity" type table, to avoid separate Signup and Reportback id's: #2523

**Comment by aaronschachter** [comment]
Might be worth revisiting this idea again. Per slack convo in the #api room: 

> When reviewing how we determine whether or not a user is signed up for a campaign, Evan (our former iOS mentor) was surprised the current user’s activity not included in the payload of a GET campaign?id=123. 
> The way the mobile app has to work without this data exposed in a campaign payload, is by querying for all of the current user’s activity upon app launch, then storing it in memory. we then traverse this array of activities (called a `DSOCampaignSignup`) when viewing a campaign. this is not ideal, because the user may have signed up on the web after launching the app.
> a 2nd scenario is 1 query to the campaign for the data, and 2nd API query to determine whether or not the user is signed up, which also isn’t ideal.

**Pull request closed without merging**
