### PR TITLE
Quick fixes for donate form CSS.

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
- Quick CSS fixes for layout issues on donate form.

These haven't been tested since my local box is broken, but they worked in the web inspector! :japanese_ogre: 

For review: @DoSomething/front-end

### CODE REVIEW

**Comment by weerd** [comment]
:+1:

**Comment by DFurnes** [comment]
Just got my Vagrant box working & tested. Made a few tiny tweaks and ready for re-review! :art:

**Comment by weerd** [comment]
Re- :+1:

**Comment by sbsmith86** [comment]
:100:

**Pull request merged**
