### PR TITLE
add textarea field to voter reg custom setting

### LINKED ISSUE #6903: Accounting for the registration deadlines in the social share stuff
#### User Story

As a member, I want to know if/when a registration deadline has passed. (especially since RTV doesn't change the messaging in their form).
#### Additional Information (optional)

[Example mockup](https://docs.google.com/drawings/d/1PU-psk5NMjW1WwlhPKAZnbSwI4omseUNrrlnAbiyDp0/edit)
#### Why This Matters

So users know when their deadlines are and if it's passed, they can't vote in the prez. election but SHOULD STILL GET REGISTERED.

@katiecrane making this issue so it's not lost. thanks!

### PR DESCRIPTION
**Pull request by katiecrane**
#### What's this PR do?

Added a textarea form field to the voter reg custom setting. The text gets passed along to the template and included above the voter reg form with the custom social share link.
#### How should this be reviewed?

To test, fill out the field (using html!!) and make sure it shows up above the form as expected. Clear it and make sure nothing crashes when there's nothing in there.
#### Any background context you want to provide?

This feature was wanted so that admins can include notes about registration deadlines and keep altering the text based on which ones have passed/are coming up/etc.
#### Relevant tickets

Fixes #6903
#### Checklist
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love. @ngjo 👋

### CODE REVIEW

**Comment by angaither** [comment]
@katiecrane should there be default text if the field isn't set?

**Comment by katiecrane** [comment]
@angaither great idea! Should probably be "Register with the form below. When you’re done -- use this custom share link to get your friends and family to register!" aka the text that's not about deadlines

**Comment by angaither** [comment]
@katiecrane errr, but maybe more generic so it's not so vote-register-y?

**Comment by katiecrane** [comment]
@angaither it's a field within the voter reg custom settings though?

**Comment by angaither** [comment]
UGH I'M SORRY. 🔍

**Comment by katiecrane** [comment]
👓  😎

**Pull request merged**
