### PR TITLE
Swap header sizes on static content. Fixes #4084.

### LINKED ISSUE #4084: Static content has inconsistentent <h> tags
Looks like the first heading is a getting a h1 and the second is getting a h2, without any modifiers.

pic

https://www.dosomething.org/about/sms-volunteer-program

cc: @julielorch @mikefantini

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
- Swap header sizes on static content. Fixes #4084.

For review: @DoSomething/front-end

### CODE REVIEW

**Comment by weerd** [comment]
Looks good. :+1: 

No header classes though?

**Comment by DFurnes** [comment]
Nah, no need here. Unless you think they're all `<h2>`s semantically? I'm not sure.

**Comment by weerd** [comment]
They're all the first headings in `<section>`s right? If so no worries then :)

**Comment by DFurnes** [comment]
Aye! Cool, that's what I thought but I never know for sure. :grimacing:

**Comment by weerd** [comment]
HTML5!

**Comment by DFurnes** [comment]
:goberserk:

**Pull request merged**
