### PR TITLE
Varnish envvar #Fixes 291

### PR DESCRIPTION
**Pull request by desmondmorris**
This is ready to go.

This requires a "vagrant provision"

### CODE REVIEW

**Comment by desmondmorris** [comment]
This needs moar love.  The env var wont stick.

@mshmsh5000 thoughts?

**Comment by mshmsh5000** [comment]
@desmondmorris 

### Idea 1

How about overwriting the varnish secret after install? Then you can hard-code the value in both places.

`/etc/varnish/secret` can be a managed file in salt: https://gist.github.com/mshmsh5000/8049305

### Idea 2

If you're already busting the secret-ness of the secret file, just make it readable in Salt. Then settings.php can dance like

``` php
$varnish_secret_file = '/etc/varnish/secret';
if (is_readable($varnish_secret_file)) {
  $conf['varnish_control_key'] = file_get_contents($varnish_secret_file);
} else {
  // Panic
}
```

**Comment by desmondmorris** [comment]
I like you bc you are smart.

**Comment by desmondmorris** [comment]
That was not supposed to be sarcastic :) 

My vote is for #1 as I think that the file_get_contents is more expensive than reading the environment variable.

**Comment by desmondmorris** [comment]
@mshmsh5000 a quick sanity check.  I ended generating a has value and adding it to a "secret: file managed by salt, as you suggested.

This will be one of those values that will need to be changed in production environments

**Comment by mshmsh5000** [comment]
Looks good. The varnish conf is moving to the [settings.local.php file](https://github.com/DoSomething/dosomething/pull/574). We can fix after we get these two PRs in.

+1 ship it value add

**Pull request merged**
