### PR TITLE
Fixes close button

### PR DESCRIPTION
**Pull request by itsjoekent**
#### What's this PR do?

tell us, what have you changed?
#### How should this be reviewed?

tell us, how can we review, to test that this works
#### Any background context you want to provide?

what else?
#### Relevant tickets

Fixes #
#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

### CODE REVIEW

**Comment by itsjoekent** [comment]
This is the error fired when you try to close onboarding. 
screen shot 2016-09-27 at 11 34 07 am

Appears "ref" is calling setupListener when the component is unmounted. Strange react stuffs? Regardless this fixes!

**Comment by weerd** [comment]
Wait, was this not tested before? 😱

**Review by weerd — APPROVED** [review]
👍

**Comment by itsjoekent** [comment]
With all of the different branches / PR's floating around i probs forgot on one of them haha

**Pull request merged**
