### PR TITLE
Programatically finding full path to font files

### PR DESCRIPTION
**Pull request by sbsmith86**
Updated the imagemagick script to find the full path of the font files and image directory programatically so we don't need to worry about it in different environments.

### CODE REVIEW

**Comment by angaither** [comment]
:+1:

**Comment by DFurnes** [comment]
I think you might be able to use the `DS_APP_ROOT` environment variable to find the path. Does using `find` have a performance hit if it has to search for the file each time?

**Comment by sbsmith86** [comment]
@DFurnes not sure we can use that variable in the shell script...

**Comment by DFurnes** [comment]
Yeah, neither am I. I think it's set when provisioning boxes, so should be available from any shell script but not entirely sure. @sergii-tkachenko or @blisteringherb?

**Comment by sergiitk** [comment]
@DFurnes, no this variable will not be available on staging and production boxes.
See https://github.com/DoSomething#5

**Comment by DFurnes** [comment]
Okay, never mind! :grin: :+1:

**Pull request merged**
