### PR TITLE
Updates Drupal core to 7.35.

### PR DESCRIPTION
**Pull request by sergiitk**
Fixes https://www.drupal.org/SA-CORE-2015-001

### CODE REVIEW

**Comment by sergiitk** [comment]
Build still says

```
Could not locate drupal version 7.35.
```

**Comment by aaronschachter** [comment]
It might take some time for the new release to propagate across the world wide web, let's hold off on merge until confirmed the build runs (and nothing breaks!).

**Comment by sergiitk** [comment]
Looks like it works now:

```
drupal-7.35 downloaded.
```

Checking if nothing breaks.

**Comment by sergiitk** [comment]
Just confirmed, build works, reset pass works.
@aaronschachter good to go?

**Comment by aaronschachter** [comment]
:+1: shippy

**Pull request merged**
