### PR TITLE
Fix spacing for button on t-shirt page.

### PR DESCRIPTION
**Pull request by DFurnes**
# Changes
- Fixes spacing for button on t-shirt page. References #3764.

For review: @DoSomething/front-end

### CODE REVIEW

**Comment by weerd** [comment]
Is it enclosed in `<p>` just to help add a top/bottom margin?

**Comment by DFurnes** [comment]
Yep, add same standard spacing that text blocks get.

**Comment by weerd** [comment]
Could we use a adjacent child selector deal... feels weird that it's a button class, but needs to have a wrapping `<p>` just for proper spacing...

something like:

```
p + .button {  margin-top: $base-spacing; }
```

**Comment by DFurnes** [comment]
That's not a bad idea. I also wonder if there's a place for an `.inline-form` type element that could house buttons and other form fields within text blocks.

**Comment by weerd** [comment]
Yeah, that could be useful :)

**Comment by DFurnes** [comment]
Closing, we'll use the `.form-actions.-inline` pattern added in Neue 6.0-beta4! :dancer:

**Pull request closed without merging**
