### PR TITLE
Hides asterisks on required form fields.

### LINKED ISSUE #869: Auth - Create an Account Required Fields Needed
First Name and Birthday should both be required fields and they should have \* indicating that they are required.

image

### PR DESCRIPTION
**Pull request by DFurnes**
Fixes #869.

Drupal.org gave some friendly advice along the way. :trollface: 
drooooopal

### CODE REVIEW

**Comment by aaronschachter** [comment]
Why not just hide the asterik with css instead of unset it?

**Comment by DFurnes** [comment]
We can, but if that's the case then we should be adding a '#required' to the first name and birthday fields as well since neither of them have it.

**Comment by DFurnes** [comment]
That being said, using a PHP hook to add inline CSS to the page with a `display: none !important` is almost certainly not the right way to be doing this.

**Comment by aaronschachter** [comment]
If first name and birthday are required, it definitely makes sense to add to the form.

This doesn't work? https://drupal.org/comment/229295#comment-229295

**Comment by angaither** [comment]
@DFurnes since these are required fields, rather not unset them as required... if adding it to first name and birthday we can do that

**Comment by angaither** [comment]
@aaronschachter jinx

**Comment by DFurnes** [comment]
@aaronschachter That'd work. I'm happy to do it that way instead.

Just read the documentation and I see that `#required` is setting validation on the server-side. Definitely agreed that we shouldn't be unsetting it, good call. Frustrating that all this stuff is intertwined though.

**Comment by angaither** [comment]
Alright, I'll make and issue and do it :ballot_box_with_check:

**Comment by DFurnes** [comment]
Pair coded with @desmondmorris, merging in.

**Pull request merged**
