### PR TITLE
Some quick fixes to errors/warnings popping up in the Log Messages.

### PR DESCRIPTION
**Pull request by weerd**
#### What's this PR do?

This PR fixes some API related bugs that cropped up during updates for the campaign run related things.
#### Where should the reviewer start?

Just pop some :eyes: on the quick changes.
#### How should this be manually tested?

Meh. We can probs just check it once on Thor.
#### Any background context you want to provide?

We were getting some log messages with errors related to these bugs and needed to be fixed to move forward.

---

@DFurnes 

CC: @jonuy @angaither

### CODE REVIEW

**Comment by DFurnes** [comment]
:+1: :boat:

**Comment by sergiitk** [comment]
:heart: :heart: :heart: Diego!

**Comment by weerd** [comment]
hehe, so much love :blush:

**Comment by sergiitk** [comment]
That's what you get for cleaning PHP errors noise!

**Pull request merged**
