### PR TITLE
Sms  disclaimer color

### PR DESCRIPTION
**Pull request by weerd**
...n template.

Resovles #2642 

@DFurnes don't be mad!

### CODE REVIEW

**Comment by DFurnes** [comment]
Why not use `$dark-gray`?

**Comment by weerd** [comment]
Waaay to dark. Basically same color as regular text. I tried it.

**Comment by DFurnes** [comment]
Gotcha. Merge away. Let's definitely take some time to think about this in the future though. :sailboat:

**Comment by weerd** [comment]
Indeed! :dancer:

**Pull request merged**
