### PR TITLE
Onboarding  button animation tweak

### PR DESCRIPTION
**Pull request by weerd**
#### What's this PR do?

This PR makes a quick update to eliminate the flash of text on the button as it changes from the loading animation, back to its original state, and then transitions to the successful action button animation.
#### How should this be reviewed?

👀 
#### Relevant tickets

Fixes 💅 
#### Checklist
- [ ] Tested on staging.

---

@DFurnes

### CODE REVIEW

**Comment by DFurnes** [comment]
Does this work in IE? I seem to remember `color: transparent` being a bit of a pain but I forget whether that was just an IE 8 thing or not.

**Comment by itsjoekent** [comment]
some interesting notes on that ^ here: http://stackoverflow.com/questions/3171586/color-transparent-is-not-working-in-internet-explorer

**Comment by weerd** [comment]
ah good call. What IE are we still supporting? Been out of the fender game for Phoenix for a bit and can't remember. 

@deadlybutter good find. I'll switch it to `visibility`.

**Comment by weerd** [comment]
errr. wait. I can't switch to visibility. That'll affect the entire button. Color specifically targets the text. I'd have to wrap it in a `span` which I'd like to avoid @_@

**Comment by DFurnes** [comment]
I think this is still good to merge, but you might need to add a fallback solid color like we do for the [`.is-loading` modifier](https://github.com/DoSomething/forge/blob/dc8d2a60ce5b09c448007a2ad5b1d353e1cd901a/scss/_components/_forms/_button.scss#L122-L123) in Forge.

> What IE are we still supporting? Been out of the fender game for Phoenix for a bit and can't remember.

Let's concentrate on supporting IE10+, but if it's easy to fix stuff up for IE8/IE9 then why not.

**Pull request merged**
