### PR TITLE
Adds run nid to view

### LINKED ISSUE #6007: Add run filtering to admin views
signup and reportback (reviewed only) needs to be able to filter by run

the default should be to display the current run
the run_nid should also be exposed in those tables

### PR DESCRIPTION
**Pull request by itsjoekent**
#### What's this PR do?

Adds run nid filter to reportback admin view
#### How should this be manually tested?

Does it filter out RB's with a diff run nid than specified?
#### Any background context you want to provide?

Showed Andrea in Slack that signup filtering appears to work already
https://thor.dosomething.org/us/node/6163/signups?uid=&mail=&source=&nid=6166&page=5
#### What are the relevant tickets?

Fixes #6007

### CODE REVIEW

**Comment by angaither** [comment]
@deadlybutter pics?

**Comment by sergiitk** [comment]
:+1:

**Comment by itsjoekent** [comment]
@angaither 

screen shot 2016-02-16 at 3 46 35 pm

**Comment by angaither** [comment]
@deadlybutter is that on all reportback views or just the reviewed tab?

**Comment by itsjoekent** [comment]
actually hmm i might have noticed something wrong, let me double check

**Comment by itsjoekent** [comment]
@angaither  where else is this view found besides the review tab?

**Comment by itsjoekent** [comment]
yeah this isnt working, i made the above RB (in the screenshot) have a NULL run nid and its still showing up

**Comment by angaither** [comment]
@deadlybutter AFAIK it's only the inbox and reviewed tab, but to avoid issues with form api and the infamous reportback reviewing bug, i think we only want this on the reviewed tab
image

**Comment by itsjoekent** [comment]
@sergii-tkachenko so @angaither said the dupes are alright, i guess ready for re-review

**Comment by itsjoekent** [comment]
screen shot 2016-02-18 at 11 21 54 am

**Comment by angaither** [comment]
@deadlybutter we probably want run id after `campaign` and it should link to the run node

**Comment by itsjoekent** [comment]
okie dokes

**Comment by itsjoekent** [comment]
@angaither done

**Comment by angaither** [comment]
:+1:

**Pull request merged**
