### PR TITLE
Removes unintended hook_user_load().

### LINKED ISSUE #4078: Fatal error introduced in v0.4.15
EntityMetadataWrapperException: Invalid data value given. Be sure it matches the required data type and format. in EntityDrupalWrapper->set() (line 736 of /var/www/beta.dosomething.org/releases/20150226192013/html/profiles/dosomething/modules/contrib/entity/includes/entity.wrapper.inc).

image

CC @barryclark @mshmsh5000 @DFurnes @angaither @weerd

### PR DESCRIPTION
**Pull request by sergiitk**
Fixes #4078.
Ref #4063.

### CODE REVIEW

**Comment by DFurnes** [comment]
Classic Dries.

classic dries

**Comment by angaither** [comment]
@sergii-tkachenko does it still interpret is a `user_load` if it's named `_dosomething_user_load`
Was following naming conventions [here](https://github.com/DoSomething/dosomething/blob/dev/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.helpers.inc#L87)

If so, perhaps we can call it ``dosomething_user_get_user` or `dosomething_user_get_simple_user` or something to stick with `module_name_function_op` naming conventions.

**Comment by sergiitk** [comment]
I'll make it `dosomething_user_get_simple_user()`.

**Comment by angaither** [comment]
:+1:

**Comment by angaither** [comment]
@DFurnes that picture will haunt me for life

**Pull request merged**
