### PR TITLE
Add Birthday and Full Mailing Address To Edit Info Tab On User Profile

### LINKED ISSUE #4520: Add Birthday and Address to the Edit Info Tab on User Profile
- Feature Summary: Campaign leads (content editors) should be able to see the street address and birthday of members.

This is helpful for leads to see for the purposes of mailing things out and highlighting reportbacks and wanting to note member age, location, etc.

Resolution: Change "edit info" tab of a user profile to include street address and zip code and birthday of members.

### PR DESCRIPTION
**Pull request by katiecrane**
fixes #4520 
- "Edit Info" tab on a user profile (user/{user_id}/info) now includes the full mailing address and birthday of users

image

cc: @namimody

### CODE REVIEW

**Comment by angaither** [comment]
cc @namimody for testing!

**Comment by angaither** [comment]
:+1:

**Comment by angaither** [comment]
wait, @katiecrane does this still 'validate'?

**Comment by katiecrane** [comment]
@angaither I didn't 'validate' anything on purpose so probably not? What needs to happen?

I see the address validation stuff in there but that all seems to happen on the form, and I'm pulling it straight from the database

**Comment by angaither** [comment]
@katiecrane ah, right but the fields don't update/save.
You also need to update the submit hook to save those values `dosomething_user_info_form_submit`

**Comment by angaither** [comment]
@katiecrane try the date like `date('y-m-d, $values['birthdate'])`

**Comment by angaither** [comment]
:+1:

**Pull request merged**
