### PR TITLE
Fixes #2389: Updates Salt config to copy Vagrant shared dir internally

### LINKED ISSUE #2389: Salt: Move Vagrant dir internal & adjust apache2 config
We want to [make Drupal run faster on Vagrant](https://github.com/DoSomething/dosomething/wiki/Make-Drupal-run-faster-on-Vagrant). Salt needs to copy the shared `/vagrant` dir to an internal dir, and adjust the apache2 vhost settings.

### PR DESCRIPTION
**Pull request by mshmsh5000**
Updates Apache vhost files. Also fixes and order of operations issue that was preventing apache2 from getting installed in the first place.

ALSO removes the Selenium package, which is a bunch of crap we don't need in here anymore.

### CODE REVIEW

**Comment by desmondmorris** [comment]
This looks good.  Giving it a spin

**Comment by mshmsh5000** [comment]
@desmondmorris Did this work out for you? Did the mount set up correctly?

**Comment by mshmsh5000** [comment]
I've run the setup from scratch on a separate OS X machine and worked out a few kinks. None of the code here needs to change, but I'm going to add docs to [the wiki page](https://github.com/DoSomething/dosomething/wiki/Make-Drupal-run-faster-on-Vagrant) for prerequisites.

**Comment by mshmsh5000** [comment]
OK, total rewrite of [the wiki page](https://github.com/DoSomething/dosomething/wiki/Make-Drupal-run-faster-on-Vagrant).

**Pull request merged**
