### PR TITLE
adds updates to signups and reportbacks to set run IDs to 0

### PR DESCRIPTION
**Pull request by chloealee**
#### What does this PR do?

Cleans up PR #6056 and sets `run_nid`s to `0`. 
#### How should this be manually tested?

See #6056 
#### What are the relevant tickets?
#6056

### CODE REVIEW

**Comment by chloealee** [comment]
@angaither @mikefantini I'm a little confused again. When we run the queries in the functions, all the data that gets returned already have `run_nid` = `0`, which is what the goal of this script is to do, right?

**Comment by angaither** [comment]
@chloealee the goal of this is to move signups and reportbacks that have been moved from `campaign_run` nodes to `campaign` nodes

**Comment by chloealee** [comment]
@angaither got it. But we changed it to set the `run_nid` = `0` in order to run Joe's script first because @mikefantini said "Reason: some runs have activity on them that should actually actually be associated with a different run." Just confused about this part now everything that gets returned from the query already had a `run_nid` = `0`?

**Comment by angaither** [comment]
@chloealee yeah, I guess you don't even have to touch that line
essentially you can 

```
select signups
join node
join field campaigns
where node type = campaign run

signup->nid = field_target_id
```

**Comment by chloealee** [comment]
@angaither just updated it to remove the line of setting `run_nid` to `0`. Does this accomplish what @mikefantini asked for?

**Comment by angaither** [comment]
:+1:

**Comment by chloealee** [comment]
cool - will merge now!

**Pull request merged**
