### PR TITLE
Translates action field guide

### LINKED ISSUE #6596: Translate Action Guide Field
#### User Story

The action guide field is not translated, but should be, as it is very likely that there are different instructions we want to give for different experiences.

https://www.dosomething.org/admin/structure/types/manage/campaign/fields/field_action_guide
#### Additional Information (optional)

The field is under the "PLAN IT" section 

image
#### Why This Matters

We want to be able to customize the experience as much as possible for different users.

cc @mnelson338

### PR DESCRIPTION
**Pull request by itsjoekent**
# WIP
#### What's this PR do?

Translates action field guide
#### How should this be reviewed?

Do action field guides still work?
Can you translate action field guides?
Does the API response still seem ok?
#### Any background context you want to provide?

no
#### Relevant tickets

Fixes #6596 
#### Checklist
- [x] staging `drush ds-global-field-fix field_action_guide`
- [ ] prod `drush ds-global-field-fix field_action_guide`

### CODE REVIEW

**Comment by itsjoekent** [comment]
everything seems to work so far for US EN, broken for global tho

screen shot 2016-07-05 at 2 20 57 pm

screen shot 2016-07-05 at 2 21 05 pm

screen shot 2016-07-05 at 2 21 09 pm

**Comment by itsjoekent** [comment]
ok works on non US now, going to attempt API.

@weerd what exactly am i looking for in the API response?

**Comment by weerd** [comment]
@deadlybutter start [here](https://github.com/DoSomething/phoenix/blob/69107297fc1f23d576e4c54b74be7d7c2cdec2d4/lib/modules/dosomething/dosomething_campaign/includes/Campaign.php#L201) and follow the 🍞 crumbs...

**Comment by itsjoekent** [comment]
@weerd sorry im just confused what exactly im looking for. I've translated fields before (eg: staff pick a few weeks ago) and never had to do API work. So im not really sure what it is im looking for or crumbs im supposed to follow

**Comment by weerd** [comment]
Typically with translation stuff we've had issues where when an entity or field is made translate-able, what Drupal returns prior to the changes might have been a simple array with data for that item, but now, with the availability of translations it comes in an associative array with keys such as `en`, `en-global`, `pr-bt` etc. So what I'm recommending is you check to make sure that the affiliate data being grabbed by the API is still working correctly and not throwing errors, etc.

So hit a few `/campaigns`, `/campaigns/:id` endpoints, etc and check the logs. See if anything broke or it's angry about offset errors etc.

**Comment by weerd** [comment]
by "crumbs" I meant follow the methods and functions calls where it deals w/ affiliate data :)

**Comment by itsjoekent** [comment]
oh gotcha 👍 

the api output seemed fine which is probably why i got confused, but ill check the logs just to make sure

**Comment by weerd** [comment]
Cool. If it all works and no issues, then awesome. 

Since we don't (can't) have tests in place we gotta do these manually and just wanted to make sure they get checked!

**Comment by itsjoekent** [comment]
dblog seems ok 👍

**Comment by itsjoekent** [comment]
not merging till all clear is given in #deploys

**Comment by itsjoekent** [comment]
@angaither good to merge?

**Comment by itsjoekent** [comment]
oh sorry just saw #deploys :facepalm:

**Comment by angaither** [comment]
@deadlybutter sure, can you release and run the script on stage after!

**Comment by itsjoekent** [comment]
oh ok sure

🚂 🚋 🚋

**Comment by itsjoekent** [comment]
script run on staging ✅ 
tested action guide usage ✅

**Pull request merged**
